---
title: '2019'
author: "Tim Ponton"
date: "17/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Data cleaning and wrangling

## Chapter 2 setup 

```{r, include=FALSE}
# Load data and clean -----------------------------------------------------
#### load packages####
library(dplyr)
library(cluster)
library(pairwiseAdonis)
library(PMCMR)
library(rstatix)
library(multcomp)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(anytime)
library(reshape2)
library(data.table)
library(tidyr)
library(plotly)
library(patchwork)
library(vegan)
library(zoo)
library(GGally)
library(jtools)
library(ggstance)
library(funrar)
library(PMCMRplus)
library(forcats)
options(scipen=5)

### read in data and fix####
 
df <- read.csv("Oct 2020/2017.2019.OR/written_df_Oct.csv")

# fix date
df$Date <- as.Date(df$Date, "%Y/%m/%d")

# add month and year columns 
df <- df %>% 
  mutate(months = months(Date), month = month(Date), year = year(Date), YEarMonth = as.yearmon(paste(year, month), "%Y %m"))

# merge date and times and coerce to proper format 
df$dateTime <- as.POSIXct(paste(df$Date, df$Time), format = "%Y-%m-%d %H:%M")

# coerce year column as factor
df$year <- as.factor(df$year)

# create a df to use as a basis
nineTeen <- df %>% 
  filter(Date >= "2018-06-01" & Date <= "2019-12-31") %>%
  filter(Site == "Primary sump", 
         Correct.Original != 0) %>% 
  filter(Species != "Diatom", 
         Classification != "Various", 
         Classification != "Ciliate", 
         Classification != "Spirotrichea", 
         Classification != "Litostomatea")



## Add FWC_mod parameters
# create first
reds <- nineTeen %>% 
  group_by(Date, Time, RowCode) %>% 
  summarise(totalCells = sum(Correct.Original, na.rm = TRUE)) %>%
  mutate(RedTide = ifelse(totalCells <= 1000, "None detected", 
                          ifelse(totalCells >= 1001 & totalCells <= 5000, "Very Low (A)", 
                                 ifelse(totalCells >= 5001 & totalCells <= 10000, "Very Low (B)", 
                                        ifelse(totalCells >= 10001 & totalCells <= 50000, "Low (A)", 
                                               ifelse(totalCells >= 50001 & totalCells <= 100000, "Low (B)", 
                                                      ifelse(totalCells >= 100001 & totalCells <= 1000000, "Medium", "High"))))))) %>% 
  mutate(FWC_mod = ifelse(totalCells >= 1 & totalCells <= 1000, "Normal", 
                          ifelse(totalCells >= 1001 & totalCells <= 10000, "Very Low", 
                                 ifelse(totalCells >= 10001 & totalCells <= 100000, "Low", 
                                        ifelse(totalCells >= 100001 & totalCells < 1000000, "Medium", "High")))))   


# Clean
maximum_fwc <- reds %>% 
  select(Date, Time, FWC_mod, totalCells) %>% 
  group_by(Date) %>% 
  mutate(maxc = max(totalCells)) %>% 
  ungroup() %>% 
  filter(totalCells == maxc) %>% 
  select(Date, FWC_mod, maxc)

# Join to basis df
nineTeenClean <- nineTeen %>% 
  left_join(maximum_fwc, by = "Date")

# Check results
# nineTeenClean %>% 
#   group_by(dateTime, FWC_mod) %>% 
#   summarise(sumC = sum(Correct.Original, na.rm = TRUE)) %>% 
#   ggplot(.,aes(x = dateTime, y = sumC)) +
#   geom_point(aes(col = FWC_mod)) +
#   geom_path() +
#   scale_y_log10()

###
         


### Summarise to daily counts####

dailyMeans <- nineTeenClean %>%
  group_by(Date, Time, dateTime, months, month, year) %>% 
  summarise(sumBio = sum(Correct.Original, na.rm = TRUE)) %>% 
  ungroup() %>% 
  group_by(Date, months, month, year) %>% 
  summarise(meanBiomass = mean(sumBio, na.rm = TRUE)) %>% 
  mutate(log1Mean = log1p(meanBiomass)) %>% 
  mutate(whatDay = weekdays(Date))

# Wrangle data ------------------------------------------------------------

## Species biomass per day
# summarise to daily means for each species
Sp_only <- nineTeenClean %>%
  group_by(Date, Species, Classification, months, month, year) %>% 
  summarise(meanCells = mean(Correct.Original, na.rm = TRUE)) %>% 
  ungroup()


## Total biomass per day
# calculate total density by adding all average species up per day they were sampled to get daily total cells
total_Sp_cells <- Sp_only %>% 
  group_by(Date, months, month, year) %>% 
  summarise(total_biomass = sum(meanCells)) %>% 
  ungroup()

## Species richness
# calculate species richness (S) by calculating number of species per day
richness <- Sp_only %>%
  filter(Classification != "Various") %>% 
  group_by(Date) %>% 
  summarise(S = n_distinct(Species))

## Diversity indices
# diversity of each day by calculating shannon index (H') for each day 

# Pivot daily counts for each species wider
div <- Sp_only %>% 
  ungroup() %>%
  select(Date, Species, meanCells) %>% 
  pivot_wider(names_from = Species, values_from = meanCells, 
              values_fill = list(meanCells = 0))





# create groupings
group_date <- div %>% 
  select(Date)

# Diversity attached to groups
group_date <- group_date %>% 
  mutate(shannon2 = diversity(div[, 2:ncol(div)], "shannon", base = 2),
         shannon = diversity(div[, 2:ncol(div)], "shannon"),
         simpson = diversity(div[, 2:ncol(div)], "simpson"), 
         Inv_simpson = diversity(div[, 2:ncol(div)], "inv"))



# evenness  by calculating Pielou’s index (J’) for each day 
# calculated as J' = H'/log(S)

# join S, H' and J' together to total daily biomass df

# group_date # H' 
# Richness # S
# total_Sp_cells # biomass


# Combine all measures
dailyDesc <- left_join(total_Sp_cells, group_date, by = "Date") %>% 
  left_join(., richness, by = "Date")

# calculate J'
dailyDesc <- dailyDesc %>% 
  mutate(J2 = shannon2/log(S), 
         J = shannon/log(S))




# Create monthly aggregates -----------------------------------------------



## Monthly averages for each species
SP_monthly <- nineTeenClean %>% 
  #filter(year != "2020") %>% 
  filter(Classification != "Various") %>% 
  group_by(months, month, year, Species, Classification) %>% 
  summarise(meanCells = mean(Correct.Original, na.rm = TRUE))





# Phyto Class diversity ---------------------------------------------------




## when were diatoms or dinos dominant
# mutate dominants
DD_dom <- Sp_only %>% 
  group_by(months, month, year, Classification) %>% 
  summarise(monthlyMean = mean(meanCells, na.rm = TRUE)) %>% 
  pivot_wider(names_from = "Classification", values_from = "monthlyMean",
              values_fill = list(monthlyMean = 0)) %>% 
  mutate(Dominant = ifelse(Diatom > Dinoflagellate, "Diatom", 
                           ifelse(Diatom < Dinoflagellate, "Dinoflagellate", "Other"))) %>% 
  pivot_longer(-c(months, month, year, YEarMonth, Season, Dominant), names_to = "Classification", values_to = "monthlyMean")

all_dom <- DD_dom %>% 
  select(-c(Classification, monthlyMean))

Diatom_dom <- DD_dom %>% 
  filter(Dominant == "Diatom") %>% 
  select(months, month, year, YEarMonth, Season, Dominant)

Dino_dom <- DD_dom %>% 
  filter(Dominant == "Dinoflagellate") %>% 
  select(months, month, year, YEarMonth, Season, Dominant)

## Join dominant class to monthly species data

Sp_monthly_with.Dom <- SP_monthly %>% 
  left_join(all_dom, by = c("months", "month", "year"))








# quantifying resources ---------------------------------------------------

#total per time
max_cells_day <- nineTeenClean %>% 
  #filter(year == "2019") %>%   # 2019 subsetted as previous years did not employ fine-scale monitoring
  group_by(Date, Time, months, month, Species) %>% 
  summarise(total.per.time = sum(Correct.Original)) %>% 
  ungroup() %>% 
  group_by(Date, Time, months, month) %>% 
  summarise(totTime = sum(total.per.time)) %>% 
  ungroup() %>% 
  group_by(Date, months, month) %>% 
  summarise(totalCells = max(totTime, na.rm = TRUE)) %>% 
  mutate(RedTide = ifelse(totalCells <= 1000, "None detected", 
                          ifelse(totalCells >= 1001 & totalCells <= 5000, "Very Low (A)", 
                                 ifelse(totalCells >= 5001 & totalCells <= 10000, "Very Low (B)", 
                                        ifelse(totalCells >= 10001 & totalCells <= 50000, "Low (A)", 
                                               ifelse(totalCells >= 50001 & totalCells <= 100000, "Low (B)", 
                                                      ifelse(totalCells >= 100001 & totalCells <= 1000000, "Medium", "High"))))))) %>% 
  mutate(FWC_mod = ifelse(totalCells >= 1 & totalCells <= 1000, "Normal", 
                          ifelse(totalCells >= 1001 & totalCells <= 10000, "Very Low", 
                                 ifelse(totalCells >= 10001 & totalCells <= 100000, "Low", 
                                        ifelse(totalCells >= 100001 & totalCells < 1000000, "Medium", "High")))))



## create df with red tide classes
maximal <- PS %>% 
  group_by(Date, months, month) %>% 
  summarise(totalCells = max(Cells.L)) %>% 
  mutate(RedTide = ifelse(totalCells <= 1000, "None detected", 
                          ifelse(totalCells >= 1001 & totalCells <= 5000, "Very Low (A)", 
                                 ifelse(totalCells >= 5001 & totalCells <= 10000, "Very Low (B)", 
                                        ifelse(totalCells >= 10001 & totalCells <= 50000, "Low (A)", 
                                               ifelse(totalCells >= 50001 & totalCells <= 100000, "Low (B)", 
                                                      ifelse(totalCells >= 100001 & totalCells <= 1000000, "Medium", "High"))))))) %>% 
  mutate(FWC_mod = ifelse(totalCells >= 1 & totalCells <= 1000, "Normal", 
                          ifelse(totalCells >= 1001 & totalCells <= 10000, "Very Low", 
                                 ifelse(totalCells >= 10001 & totalCells <= 100000, "Low", 
                                        ifelse(totalCells >= 100001 & totalCells < 1000000, "Medium", "High")))))


# calculate the number of samples collected per day (FIND SOLUTIONS)
Time_count <- nineTeenClean %>% 
  group_by(Date) %>% 
  summarise(count_times = n_distinct(Time))

Time_count %>% 
  left_join(select(nineTeenClean, Date, months, month, year, YEarMonth), by = "Date", keep = FALSE) %>% 
  group_by(months, month, year) %>% 
  summarise(meanTimeCounts = mean(count_times, na.rm = TRUE))


# make classes as.factor
max_cells_day$FWC_mod <- as.factor(max_cells_day$FWC_mod)
# check factors
levels(max_cells_day$FWC_mod)
# set order of factors 
max_cells_day$FWC_mod <-  factor(max_cells_day$FWC_mod, 
                                     levels = c("High","Medium", "Low", "Very Low", "Normal"))



# calculate average counting times/day
left_join(max_cells_day, Time_count, by = "Date") %>% 
  ungroup() %>% 
  summarise(meanc = mean(count_times, na.rm = TRUE))


# merge red tide dates and number of times sampled per day and filter above avergae counting days
resources <- left_join(max_cells_day, Time_count, by = "Date") %>% 
  filter(count_times > 0) # > average counts per day

# number of times different red tide classes were experienced per  --------

#total per time
all_max_cells_day <- PS %>% 
  group_by(Date, Time, months, month, Species) %>% 
  summarise(total.per.time = sum(Cells.L)) %>% 
  ungroup() %>% 
  group_by(Date, Time, months, month) %>% 
  summarise(totTime = sum(total.per.time)) %>% 
  ungroup() %>% 
  group_by(Date, months, month) %>% 
  summarise(totalCells = max(totTime, na.rm = TRUE)) %>% 
  mutate(RedTide = ifelse(totalCells <= 1000, "None detected", 
                          ifelse(totalCells >= 1001 & totalCells <= 5000, "Very Low (A)", 
                                 ifelse(totalCells >= 5001 & totalCells <= 10000, "Very Low (B)", 
                                        ifelse(totalCells >= 10001 & totalCells <= 50000, "Low (A)", 
                                               ifelse(totalCells >= 50001 & totalCells <= 100000, "Low (B)", 
                                                      ifelse(totalCells >= 100001 & totalCells <= 1000000, "Medium", "High"))))))) %>% 
  mutate(FWC_mod = ifelse(totalCells >= 1 & totalCells <= 1000, "Normal", 
                          ifelse(totalCells >= 1001 & totalCells <= 10000, "Very Low", 
                                 ifelse(totalCells >= 10001 & totalCells <= 100000, "Low", 
                                        ifelse(totalCells >= 100001 & totalCells < 1000000, "Medium", "High")))))



# make classes as.factor
all_max_cells_day$FWC_mod <- as.factor(all_max_cells_day$FWC_mod)
# check factors
levels(all_max_cells_day$FWC_mod)
# set order of factors 
all_max_cells_day$FWC_mod <-  factor(all_max_cells_day$FWC_mod, 
                                 levels = c("High","Medium", "Low", "Very Low", "Normal"))


# join year columns, tally per class per month per year (remove 2020) (CORRECT)
are <- all_max_cells_day %>% 
  left_join(select(PS, Date, months, year, YEarMonth), by = c("Date", "months"), keep = FALSE) %>%
  filter(year != "2020") %>% 
  group_by(months, month, year, FWC_mod) %>% 
  distinct() %>% 
  count() %>% 
  arrange(desc(n))


# join year columns, tally per class per month per year (remove 2020)
re <- all_max_cells_day %>% 
  left_join(select(PS, Date, months, year, YEarMonth), by = c("Date", "months"), keep = FALSE) %>%
  filter(year != "2020") %>% 
  group_by(months, month, year, FWC_mod) %>% 
  count()

# join year columns, tally per class per month per year (remove 2020)
RT.classNumbers_monthYear <- all_max_cells_day %>% 
  left_join(select(PS, Date, months, year, YEarMonth), by = "Date", keep = FALSE) %>%
  filter(year != "2020") %>% 
  group_by(months.x, month, year, YEarMonth, FWC_mod) %>% 
  tally() %>% 
  arrange(desc(n))



# NMDS --------------------------------------------------------------------

# dataframe of species with their abbreviations
Sp_abbre <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  select(Species) %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  distinct()

# finding relative abundance across total samples
te <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(Sp_abb) %>% 
  summarise(averageDens = mean(meanCells, na.rm = TRUE)) %>% 
  pivot_wider(names_from = Sp_abb, values_from = averageDens, 
              values_fill = list(averageDens = 0)) 

tet <- make_relative(as.matrix(te))

tet <- as.data.frame(tet)

se <- tet %>% 
  gather(key = "Sp_abb", value = "abun") %>% 
  arrange(desc(abun)) %>% 
  filter(abun > 0.003)

se %>% 
  summarise(S = n_distinct(Sp_abb))


ggplotly(ggplot(data = se, aes(x = reorder(Sp_abb, abun), y = abun)) +
  geom_col() +
  coord_flip())


# relative abudance per month
mte <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(months, Sp_abb) %>% 
  summarise(averageDens = mean(meanCells, na.rm = TRUE)) %>% 
  pivot_wider(names_from = Sp_abb, values_from = averageDens, 
              values_fill = list(averageDens = 0)) %>% 
  remove_rownames %>% 
  column_to_rownames(var="months")

mtet <- make_relative(as.matrix(mte))

mtet <- as.data.frame(mtet)%>% 
  rownames_to_column(var = "months")

# HAB species vs everything else relative abundance 
# Get relative abundance per month for each species
month.rel <- as.data.frame(
  make_relative(
  as.matrix(
  Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(YEarMonth, Sp_abb) %>% 
  summarise(averageDens = mean(meanCells, na.rm = TRUE)) %>% 
  pivot_wider(names_from = Sp_abb, values_from = averageDens, 
              values_fill = list(averageDens = 0)) %>% 
  remove_rownames %>% 
  column_to_rownames(var="YEarMonth")))) %>% 
  rownames_to_column(var = "YEarMonth")

# add month order into df
monthOrder <- Sp_only %>% 
  ungroup() %>% 
  select(YEarMonth, months, month, year)

monthOrder$YEarMonth <- as.factor(monthOrder$YEarMonth)

# join month order, reorder columns and pivot longer
month.rel <- month.rel %>%
  ungroup() %>% 
  left_join(monthOrder, by = "YEarMonth", keep = FALSE) %>% 
  select(YEarMonth, months, month, year, everything()) %>% 
  pivot_longer(-c(YEarMonth, months, month, year), names_to = "Sp_abb", values_to = "abun") %>% 
  inner_join(Sp_abbre, by = "Sp_abb")
  

# find dom species
dom_sp <- month.rel %>% 
  group_by(Sp_abb) %>%
  filter(abun > 0.5) %>% 
  ungroup()




mse <- mtet %>%
  pivot_longer(-months, names_to = "Sp_abb", values_to = "abun") %>% 
  group_by(months) %>% 
  arrange(desc(abun)) %>% 
  filter(abun > 0.01)

mse %>% 
  ungroup() %>% 
  summarise(S = n_distinct(Sp_abb))



## Overall months combined
# summarise species to monthly aggre. and abbrev. species names after log10 transforming
monthly.species <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(months, Sp_abb) %>% 
  summarise(averageDens = log10(mean(meanCells, na.rm = TRUE))) %>% 
  semi_join(., mse, by = "Sp_abb")


monthly.species %>% 
  semi_join(., mse, by = "Sp_abb") %>% 
  ungroup() %>% 
  summarise(S = n_distinct(Sp_abb))

# Pivot wider and change months column to rowname
monthly.species_wide <- monthly.species %>% 
  pivot_wider(names_from = Sp_abb, values_from = averageDens, 
              values_fill = list(averageDens = 0)) %>% 
  remove_rownames %>% 
  column_to_rownames(var="months")



# whether to use relative abundance for NMDS or not
# calculate relative abundances per month
monthly.species_wide <- as.matrix(monthly.species_wide)
rel_monthly.Sp <- make_relative(monthly.species_wide)


# run NMDS (check to see what data are being used, rel abund or ave counts)
NMDStestmonth <- metaMDS(monthly.species_wide, k = 3, autotransform = FALSE, trymax = 100)

# check results
NMDStestmonth
# stressplot of NMDS results
stressplot(NMDStestmonth)

# End



#### To plot NMDS using ggplot2 usign B. Cloete methods
monthly.species_wide <- monthly.species %>% 
  pivot_wider(names_from = Sp_abb, values_from = averageDens, 
              values_fill = list(averageDens = 0))

com <- monthly.species_wide[, 2:ncol(monthly.species_wide)]
m_com <- as.matrix(com)

NMDStestmonth <- metaMDS(m_com, k = 3, autotransform = FALSE, trymax = 100)

data.scores <- as.data.frame(scores(NMDStestmonth))
data.scores$site <- monthly.species_wide$months

# extract NMDS scores (x and y coordinates)
data.scores = as.data.frame(scores(nmds))

# add columns to data frame
data.scores$site = abun$SITE
data.scores$veg = abun$VEG

# ## Original try, with no Abrev. Kept for just incase 
# testmonth <- Sp_only %>%
#   ungroup() %>% 
#   filter(Species != "Diatom") %>% 
#   group_by(months, Species) %>% 
#   summarise(averageDens = mean(meanCells, na.rm = TRUE)) %>%
#   pivot_wider(names_from = Species, values_from = averageDens, 
#               values_fill = list(averageDens = 0)) %>% 
#   remove_rownames %>% 
#   column_to_rownames(var="months")
# 
# 
# NMDStestmonth <- metaMDS(testmonth, k = 3, autotransform = TRUE)
# 
# NMDStestmonth
# stressplot(NMDStestmonth)

```



## Chapter 3 setup


```{r, include=FALSE, warning=FALSE}

# run  lines from 'Building Chp2' until before subsetting PS only 

## load data
# size classes of dominant species 
sp_sizes <- read.csv("Updated data from April 2020/Dominant sizes.csv", stringsAsFactors = FALSE)

# subset dates for when both Ps and ADF were sampled ----------------------

ps_adf <- df %>% 
  group_by(Date) %>% 
  filter(Classification != "Various", Date != "2019-12-17", Date != "2019-02-17") %>% 
  filter(all(c("After Drumfilter", "Primary sump") %in% Site)) %>% 
  filter(Site %in% c("After Drumfilter", "Primary sump")) %>% 
  filter(Species != "Diatom")


# correct the order of sites (PS before ADf)
ps_adf$Site <- as.factor(ps_adf$Site)
ps_adf$Site <-  factor(ps_adf$Site, 
                       levels = c("Primary sump", "After Drumfilter"))


# correct levels of FWC_mod classes
ps_adf$FWC_mod <- as.factor(ps_adf$FWC_mod)
ps_adf$FWC_mod <-  factor(ps_adf$FWC_mod, 
                   levels = c("High","Medium", "Low", "Very Low", "Normal"))



# Daily metrics of different sites ----------------------------------------

## calculate biomass evennes richness diversity per day/ week for each site
# average counts for each species per day
Sp.only_filter <- ps_adf %>% 
  group_by(Date, Site, Species, Classification, months, month, year, 
           YEarMonth, Season, SeasonOrder, RedTide, FWC_mod) %>% 
  summarise(meanCells = mean(Cells.L, na.rm = TRUE))

# total biomass per day (all species added together per day)
total_sp_filter <- Sp.only_filter %>% 
  group_by(Date, Site, months, month, year, YEarMonth, Season, FWC_mod) %>% 
  summarise(total_biomass = sum(meanCells)) %>% 
  ungroup()

# richness
richness_filter <- Sp.only_filter %>% 
  group_by(Date, Site) %>% 
  summarise(S = n_distinct(Species))


# diversity
# pivot species wider
div_filter <- Sp.only_filter %>% 
  ungroup() %>% 
  select(Date, Site, Species, meanCells) %>% 
  pivot_wider(names_from = Species, values_from = meanCells, 
              values_fill = list(meanCells = 0))

# create group
group_filter <- div_filter %>% 
  select(Date, Site)

# diversity for each day, and site
group_filter <- group_filter %>% 
  mutate(shannon2 = diversity(div_filter[, 3:ncol(div_filter)], "shannon", base = 2),
       shannon = diversity(div_filter[, 3:ncol(div_filter)], "shannon"),
       simpson = diversity(div_filter[, 3:ncol(div_filter)], "simpson"), 
       Inv_simpson = diversity(div_filter[, 3:ncol(div_filter)], "inv"))


# Join all metrics

dailydesc_filter <- left_join(total_sp_filter, group_filter, by = c("Date", "Site")) %>% 
  left_join(., richness_filter, by = c("Date", "Site"))


# calculate evenness
dailydesc_filter <- dailydesc_filter %>% 
  mutate(J2 = shannon2/log(S), 
       J = shannon/log(S))



# Comparing biomass at different points on farm  --------------------------------------------------------

# subset specific day when many sites had been sampled (2019-02-26)
## Filter unknown sites

# codecounts are filtered for all sampels after 12pm (afternoon)
# mutated time period to indicae when sampels were taken 
pos <- df %>% 
  filter(Date == "2019-02-26") %>% 
  filter(Site != "Unknown") %>% 
  # filter(CodeCount >= "3518" & CodeCount <= "3550") %>% 
  mutate(`Day Time period` = ifelse(Time %in% c("01:00", "03:00", "05:00", 
                                    "06:00", "07:45", "09:30", "10:15", "10:45"), 
                                    "Morning", "Afternoon"))
  
# Fix order of time period samples
pos$`Day Time period` <- as.factor(pos$`Day Time period`)
pos$`Day Time period` <-factor(pos$`Day Time period`, levels = c("Morning", "Afternoon"))

# fix order of Locations
pos$Location <- factor(pos$Location, levels = c("Incoming seawater", "Seaview farm", "Hatchery farm", "Bergsig farm"))

# Ind species fluctuations ------------------------------------------------

# daily means
# pivot sites wider
# calculate Ps minus ADf
sp_site_diff_daily <- Sp.only_filter %>% 
  pivot_wider(names_from = Site, values_from = meanCells, 
              values_fill = list(meanCells = 0)) %>% 
  mutate(site.Diff = `Primary sump` - `After Drumfilter`)


# pick top n species 
top_species <- Sp.only_filter %>% 
  group_by(Species, Classification) %>% 
  summarise(Sp_average = mean(meanCells, na.rm = TRUE)) %>% 
  arrange(desc(Sp_average)) %>% 
  ungroup() %>% 
  top_n(3) %>% 
  ungroup()


# filter top n species
sp_site_diff_daily <- sp_site_diff_daily %>% 
  filter(Species %in% top_species$Species)


# Average species to monthly means
# pivot sites wider
# calculate Ps minus ADf
sp_site_diff_monthly <- Sp.only_filter %>% 
  group_by(Site, months, month, Species, Classification) %>% 
  summarise(monthly.mean = mean(meanCells, na.rm = TRUE)) %>% 
  pivot_wider(names_from = Site, values_from = monthly.mean, 
              values_fill = list(monthly.mean = 0)) %>% 
  mutate(site.Diff = `Primary sump` - `After Drumfilter`)

# pick top n species 
top_species <- Sp.only_filter %>% 
  group_by(Species, Classification) %>% 
  summarise(Sp_average = mean(meanCells, na.rm = TRUE)) %>% 
  arrange(desc(Sp_average)) %>% 
  ungroup() %>% 
  top_n(3) %>% 
  ungroup()

# calculate mean size class
sp_sizes <- sp_sizes %>% 
  group_by(Species) %>% 
  mutate(mean_length = mean(min_length:max_length, na.rm = TRUE))

top_species <- top_species %>% 
  left_join(sp_sizes, by = "Species")


site_size <- Sp.only_filter %>% 
  group_by(Site, months, month, Species, Classification) %>% 
  #summarise(monthly.mean = mean(meanCells, na.rm = TRUE)) %>% 
  filter(Species %in% top_species$Species) %>% 
  left_join(top_species, by = "Species") %>% 
  ungroup()
  








# NMDS if sites influence species biomass --------------------------------








```


# Chapter plots

## Chapter 2 

```{r, warning=FALSE}


###### Chapter 2 Phytoplanktpn #########
## PHYTOPLANKTON COMMUNITY DIVERSITY ETC -----------------------------------





#'*year-monthly biomass (1) ---------------*
# Plot monthly total biomass, comparing years
biomass.YM <- Sp_only %>% 
  group_by(months, month, year, Season) %>% 
  summarise(monthlyMean = mean(meanCells, na.rm = TRUE), 
            monthlyN = n(),
            monthlySD = sd(meanCells, na.rm = TRUE), 
            monthlySE = sd(meanCells, na.rm = TRUE)/sqrt(n())) %>% 
  arrange(desc(-monthlyMean)) %>% 
  ggplot(., aes(x = reorder(months, month), y = monthlyMean, col = year)) +
  geom_point() +
  geom_errorbar(aes(ymin = monthlyMean - monthlySE, ymax = monthlyMean + monthlySE), width=0.2) +
  scale_y_log10() +
  xlab("Months") +
  ylab("Log10 Cells/L") + 
  labs(col = "Year") +
  ggtitle("Comparing the log10 monthly mean phytoplankton counts between three consecutive years, with their standard error bars") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

biomass.YM


# STATS for biomass differences between years and months 

sp_mat <- Sp_only %>% 
  group_by(month, year, Species) %>% 
  summarise(avg = mean(meanCells, na.rm = TRUE)) %>% 
  pivot_wider(names_from = "Species", values_from = "avg", 
              values_fill = list(avg = 0))

sp_mat <- Sp_only %>% 
  ungroup() %>% 
  select(Date, months, year, Species, meanCells) %>% 
  pivot_wider(names_from = "Species", values_from = "meanCells", 
              values_fill = list(meanCells = 0))

# 
# com <- sp_mat[, 4:ncol(sp_mat)]
# com <- as.matrix(com)
# com <- vegdist(com, distance = "bray")
# sp_grou <- sp_mat[, 2:3]


#ano <- anosim(com, grouping = sp_grou$year, distance = "bray")
#ano


#adon <- adonis2(com ~ months, data = sp_grou, method = "bray", permutations = 999)





###############


#'*year-monthly metrics (1)*
## comparing years over months for indices



#'*(1) ------------------*
# Richness
richness.YM <- dailyDesc %>% 
  group_by(months, month, year, Season) %>% 
  summarise(monthlyRichness = mean(S, na.rm = TRUE), 
            monthlyRichnessN = n(),
            monthlyRichnessSD = sd(S, na.rm = TRUE), 
            monthlyRichnessSE = sd(S, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = (monthlyRichness), col = year, group = year)) +
  geom_point(size = 1) +
  #geom_line(size = 0.8) +
  geom_errorbar(aes(ymin = monthlyRichness - monthlyRichnessSE, ymax = monthlyRichness + monthlyRichnessSE), width=0.2) +
  xlab("Months") +
  ylab("Richness") + 
  # ggtitle("Comparing the monthly species richness of phytoplankton counts between three consecutive years ") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

ggplotly(richness.YM)

#'*(1) -----------------*
# Evenness (J')
evenness.YM <- dailyDesc %>% 
  group_by(months, month, year, Season) %>% 
  summarise(monthlyEvenness = mean(J, na.rm = TRUE), 
            monthlyEvennessN = n(),
            monthlyEvennessD = sd(J, na.rm = TRUE), 
            monthlyEvennessSE = sd(J, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = (monthlyEvenness), col = year, group = year)) +
  geom_point(size = 1) +
  #geom_line(size = 0.8) +
  geom_errorbar(aes(ymin = monthlyEvenness - monthlyEvennessSE, ymax = monthlyEvenness + monthlyEvennessSE), width=0.2) + 
  xlab("Months") +
  ylab("J'") + 
  # ggtitle("Comparing the monthly species evenness (J') of phytoplankton counts between three consecutive years") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

#'*(1) ---------------*
# Shannon
shannon.YM <- dailyDesc %>% 
  group_by(months, month, year, Season) %>% 
  summarise(monthlyshannon = mean(shannon, na.rm = TRUE), 
            monthlyshannonN = n(),
            monthlyshannonsD = sd(shannon, na.rm = TRUE), 
            monthlyshannonSE = sd(shannon, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = (monthlyshannon), col = year, group = year)) +
  geom_point(size = 1) +
  #geom_line(size = 0.8) +
  geom_errorbar(aes(ymin = monthlyshannon - monthlyshannonSE, ymax = monthlyshannon + monthlyshannonSE), width=0.2) +
  xlab("Months") +
  ylab("H'") + 
  # ggtitle("Comparing the monthly Shannon (H') Index of Diversity of phytoplankton between three consecutive years") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))


#'*(1) ----------------*
# Simpson
simpson.YM <- dailyDesc %>% 
  group_by(months, month, year, Season) %>% 
  summarise(monthlysimpson = mean(simpson, na.rm = TRUE), 
            monthlysimpsonN = n(),
            monthlysimpsonsD = sd(simpson, na.rm = TRUE), 
            monthlysimpsonSE = sd(simpson, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = (monthlysimpson), col = year, group = year)) +
  geom_point(size = 1) +
  #geom_line(size = 0.8) +
  geom_errorbar(aes(ymin = monthlysimpson - monthlysimpsonSE, ymax = monthlysimpson + monthlysimpsonSE), width=0.2) + 
  xlab("Months") +
  ylab("Simpson Index of Diversity") + 
  ggtitle("Comparing the monthly Simpson Index of Diversity of phytoplankton between three consecutive years") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))


# Figure out how to plot these
# Must 1 legend be shown? ANd remove middle ad top x axis labels?
# Capitalise legend title (labs(col = ""))
biomass.YM
richness.YM/evenness.YM/shannon.YM
simpson.YM



#'*This was added late*
# Plot dominants with others greyed out 
# HAB species vs everything else relative abundance 
# Get relative abundance per month for each species
month.rel <- as.data.frame(
  make_relative(
    as.matrix(
      Sp_only %>%
        ungroup() %>% 
        filter(Species != "Diatom") %>% 
        mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
        group_by(YEarMonth, Sp_abb) %>% 
        summarise(averageDens = mean(meanCells, na.rm = TRUE)) %>% 
        pivot_wider(names_from = Sp_abb, values_from = averageDens, 
                    values_fill = list(averageDens = 0)) %>% 
        remove_rownames %>% 
        column_to_rownames(var="YEarMonth")))) %>% 
  rownames_to_column(var = "YEarMonth")

# add month order into df
monthOrder <- Sp_only %>% 
  ungroup() %>% 
  select(YEarMonth, months, month, year)

monthOrder$YEarMonth <- as.factor(monthOrder$YEarMonth)

Sp_abbre <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  select(Species) %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  distinct()


# join month order, reorder columns and pivot longer
month.rel <- month.rel %>%
  ungroup() %>% 
  left_join(monthOrder, by = "YEarMonth", keep = FALSE) %>% 
  select(YEarMonth, months, month, year, everything()) %>% 
  pivot_longer(-c(YEarMonth, months, month, year), names_to = "Sp_abb", values_to = "abun") %>% 
  inner_join(Sp_abbre, by = "Sp_abb")


# find dom species
dom_sp <- month.rel %>% 
  group_by(months) %>%
  top_n(1, abun) %>% 
  ungroup()

# calc top species for each month
dsp <- month.rel %>% 
  group_by(month, Species) %>% 
  summarise(meanRel = mean(abun, na.rm = TRUE)) %>% 
  ungroup() %>% 
  group_by(month) %>% 
  top_n(1, meanRel)


# plot yearly fluctuations for each of the top species
ggplot() + 
  geom_point(data = month.rel %>% 
               filter(Species %in% dsp$Species), 
             aes(x = reorder(months, month), 
                 y = abun, group = year, col = year), size = 1) +
  geom_line(data = month.rel %>% 
              filter(Species %in% dsp$Species), 
            aes(x = reorder(months, month), 
                y = abun, group = year, col = year), size = 1) +
  facet_wrap(~Species, ncol = 2) +
  theme_classic() +
  xlab("Months") +
  ylab("Relative abundance") + 
  labs(col = "Phytoplankton species") +
  ggtitle("Fluctuations in the relative abundances of dominant phytoplankton species on a monthly aggregate") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

ggplotly(ggplot() + 
  geom_point(data = month.rel %>% 
               filter(Species %in% dsp$Species), 
             aes(x = reorder(months, month), 
                 y = abun, group = year, col = year), size = 1) +
  geom_line(data = month.rel %>% 
              filter(Species %in% dsp$Species), 
            aes(x = reorder(months, month), 
                y = abun, group = year, col = year), size = 1) +
  facet_wrap(~Species, ncol = 2) +
  theme_classic() +
  xlab("Months") +
  ylab("Relative abundance") + 
  labs(col = "Phytoplankton species") +
  ggtitle("Fluctuations in the relative abundances of dominant phytoplankton species on a monthly aggregate") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5)))




# phyto class diversity --------------------------------------------------

#'*[Stacked bar graph] of different phyto classes, by year-months -------------*
# from Sp_Only df all years together
Sp_only %>% 
  group_by(months, month, Season, Classification) %>% 
  summarise(monthlyMean = mean(meanCells, na.rm = TRUE)) %>% 
  ggplot(., aes(x = reorder(months, month), y = monthlyMean, fill = Classification)) +
  geom_bar(stat = "Identity", position = "fill", col = "black") +
  xlab("Months") +
  ylab("Proportion monthly mean") + 
  labs(fill = "Phytoplankton class") +
  ggtitle("Comparing the proportion of mean monthly counts between 
          phytoplankton classes over three consecutive years") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))









#'*[Stacked bar graph] of different phyto classes, by months, facetd by year ------------------*
# from Sp_Only df facet_wrap(~year)
Sp_only %>% 
  group_by(months, month, year, Season, Classification) %>% 
  summarise(monthlyMean = mean(meanCells, na.rm = TRUE)) %>% 
  ggplot(., aes(x = reorder(months, month), y = monthlyMean, fill = Classification)) +
  geom_bar(stat = "Identity", position = "fill", col = "Black") +
  facet_wrap(~year, ncol = 1) +
  xlab("Months") +
  ylab("Proportion monthly mean") + 
  labs(fill = "Phytoplankton class") +
  ggtitle("Comparing the proportion of mean monthly counts between phytoplankton 
          classes over three consecutive years") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))




# NMDS --------------------------------------------------------------------



#'*Use to show all species 97 sp --*
# All species
allsp <- ggplot(data = mtet %>%
                  pivot_longer(-months, names_to = "Sp_abb", values_to = "abun") %>% 
                  group_by(months) %>% 
                  arrange(desc(abun)), aes(x = reorder(Sp_abb, abun), y = abun)) +
  geom_col(position = "Dodge") +
  coord_flip() +
  xlab("Species") +
  ylab("Relative abundance") +
  ggtitle("Relative abundance of species (97)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))


#'*Use to show dom species species 73 sp --*
# Species above relative abundance of 0.01 per month
domsp <- ggplot(data = mtet %>%
                  pivot_longer(-months, names_to = "Sp_abb", values_to = "abun") %>% 
                  group_by(months) %>% 
                  arrange(desc(abun)) %>% 
                  filter(abun > 0.01), aes(x = reorder(Sp_abb, abun), y = abun)) +
  geom_col(position = "Dodge") +
  coord_flip() +
  xlab("Species") +
  ylab("Relative abundance") +
  ggtitle("Species with a relative abundance > 0.01 per month (73)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))


allsp / domsp


#'*[NMDS] check what it is based on i.e relative abundance or actual counts ------*
plot(NMDStestmonth)
ordiplot(NMDStestmonth,type="n")
orditorp(NMDStestmonth,display="species",col="red",air=0.01)
orditorp(NMDStestmonth,display="sites",cex=1.25,air=0.01)




## RED TIDE CLASSES --------------------------------------------------------


#'*Compare Red tide classes per month ---------*
# Compare the proportion of differnt red tide classes per month over the three years


ggplot(are, aes(x = reorder(months, month), y = n, fill = FWC_mod)) +
  geom_bar(stat = "Identity", position = "fill", col = "black") +
  facet_wrap(~year, ncol = 1) +
  xlab("Months") +
  ylab("Proportion number of days") + 
  labs(fill = "Red Tide class") +
  ggtitle("The proportion of different red tide classes per month over the three years") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))


ggplot(re, aes(x = reorder(months, month), y = n, fill = FWC_mod)) +
  geom_bar(stat = "Identity", position = "fill", col = "black") +
  facet_wrap(~year, ncol = 1) +
  xlab("Months") +
  ylab("Proportion number of days") + 
  labs(fill = "Red Tide class") +
  ggtitle("The proportion of different red tide classes per month over the three years") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

# ggplot(RT.classNumbers_monthYear, aes(x = reorder(months.x, month), y = n, fill = FWC_mod)) +
#   geom_bar(stat = "Identity", position = "fill", col = "black") +
#   facet_wrap(~year, ncol = 1) +
#   xlab("Months") +
#   ylab("Proportion number of days") + 
#   labs(fill = "Red Tide class") +
#   ggtitle("The proportion of different red tide classes per month over the three years") +
#   theme_classic() +
#   theme(plot.title = element_text(hjust = 0.5))




## RESOURCES ---------------------------------------------------------------


#'*Compare overall cells vs dates, sized by counting times ------------*
# how do counting times change over time, linked to total cells 
left_join(max_cells_day, Time_count, by = "Date") %>% 
  filter(count_times > 0) %>% 
  ggplot(., aes(x = Date, y = log(totalCells))) +
  geom_point(aes(col = FWC_mod, size = count_times)) +
  geom_line() +
  xlab("Date") +
  ylab("Log Phytoplankton counts") + 
  labs(col = "Red Tide class", size = "Samples collected per day") +
  ggtitle("Investigating how sampling frequency varied in relation to 
          red tide severity in 2019") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))


#'* USE TO COMPARE EXCLUDING ALL vs BELOW AVERAGE REGRESSIONS [Scatter and relationship line (smooth)] used to show counting times correlation, above daily counting average ------------*
# correlation between total cells counted and numebr of times counted per day
ggplot(left_join(max_cells_day, Time_count, by = "Date") %>% 
         filter(count_times > 0), aes(x = log(totalCells), y = count_times)) +
  geom_point(aes(col = FWC_mod)) +
  geom_hline(yintercept = 3.17, size = 1) +
#  geom_smooth(method = "lm", aes(col = FWC_mod), se = FALSE) +
#  geom_smooth(method = "loess", se = FALSE) +
  xlab("Log Cells/L") +
  ylab("Number samples collected per day") + 
  labs(col = "Red Tide class") +
  ggtitle("Relationship between Cells/L counted and number of samples collected per day, 
          when different Red tide severity classes were experienced") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))






```


## Chapter 3


```{r, warning=FALSE}


####### Chapter 3 Filters ################  


## PHYTOPLANKTON FLUCTUATIONS BETWEEN SITES --------------------------------



# summarise down to monthly measurements to compare sites [boxplot graph]

#'* Graphs for Aim 1a -------------*

# DO NOT USE 
# biomass
ggplot(data = dailydesc_filter, aes(x = reorder(months, month), y = total_biomass, fill = Site)) +
  geom_boxplot() +
  xlab("Months") +
  ylab("Cells/L") + 
  labs(fill = "Site") +
  ggtitle("Compare the difference in biomass of phytoplankton between the two sites, for three consecutive months") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

# Line version
ggplot(data = dailydesc_filter, aes(x = Date, y = total_biomass, col = Site)) +
  geom_line(size = 1) +
  facet_wrap(~reorder(months, month), ncol = 1, scales = "free_x")


# Point with errorbar version
Sp.only_filter %>% 
  group_by(months, month, year, YEarMonth, Site) %>% 
  summarise(mean_cells = mean(meanCells, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(meanCells, na.rm = TRUE), 
            se_cells = sd(meanCells, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = mean_cells, col = Site, group = Site)) +
  geom_point() +
#  geom_line() +
  geom_errorbar(aes(ymin = mean_cells - se_cells, ymax = mean_cells + se_cells), width=0.2) +
  xlab("Months") +
  ylab("Cells/L") + 
  labs(fill = "Site") +
#  ggtitle("") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))




## Point errorbars can be done for the metrics  too if necessary ##

# richness
ggplot(data = dailydesc_filter, aes(x = reorder(months, month), y = S, fill = Site)) +
  geom_boxplot() +
  xlab("Months") +
  ylab("Number of species") + 
  labs(fill = "Site") +
  ggtitle("Compare the difference in species richness of phytoplankton between 
          the two sites, for three consecutive months of 2019") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

# evenness
ggplot(data = dailydesc_filter, aes(x = reorder(months, month), y = J, fill = Site)) +
  geom_boxplot() +
  xlab("Months") +
  ylab("Pielou's (J') Evenness") + 
  labs(fill = "Site") +
  ggtitle("Compare the difference in species evenness (J') of phytoplankton between 
          the two sites, for three consecutive months of 2019") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

# diversity
ggplot(data = dailydesc_filter, aes(x = reorder(months, month), y = shannon, fill = Site)) +
  geom_boxplot() +
  xlab("Months") +
  ylab("Shannon Index of Diversity") + 
  labs(fill = "Site") +
  ggtitle("Compare the difference in Shannon index of diversity between phytoplankton species between 
          the two sites, for three consecutive months of 2019") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))






## DOMINANT SPECIES DENSITIES BETWEEN SITES --------------------------------




#'* used to back up ind spe graph (Aim 2), can possibly do stats on this ---------*
# [Stacked bar graph] comparing PS and ADf biomass on monthly level (more broad than above)
Sp.only_filter %>% 
  group_by(Site, months, month) %>% 
  summarise(monthly.mean = mean(meanCells, na.rm = TRUE)) %>% 
  ggplot(., aes(x = reorder(months, month), y = monthly.mean, fill = Site)) +
  geom_bar(stat = "Identity", position = "fill") +
  geom_hline(yintercept = 0.5, col = "black") +
  xlab("Months") +
  ylab("Proportion momthly mean Cells/L") + 
  labs(fill = "Site") +
  ggtitle("The proportion of cells counted between the Primary sump and After Drumfilter 
          for three consecutive months of 2019") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))




#'* Graph for Aim 2 -----------*
# [Stacked bargraph] of Top n species, comparing monthly averages between two sites
Sp.only_filter %>% 
  group_by(Site, months, month, Species, Classification) %>% 
  summarise(monthly.mean = mean(meanCells, na.rm = TRUE)) %>% 
  filter(Species %in% top_species$Species) %>% 
  ggplot(., aes(x = reorder(months, month), y = monthly.mean, fill = Site)) +
  geom_bar(stat = "Identity", position = "fill") +
  geom_hline(yintercept = 0.5, col = "black") +
  #coord_flip() +
  facet_wrap(~ reorder(Species, -monthly.mean), ncol = 2) +
  xlab("Months") +
  ylab("Proportion momthly mean Cells/L") + 
  labs(fill = "Site") +
  ggtitle("The proportion of cells counted between the Primary sump and After Drumfilter for the 
          top four dominant species for three consecutive months of 2019") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))










```


# Chapter stats

```{r Chapter 2}
#### Biomass #####
# Calculate number of days sampled
Sp_only %>% 
  ungroup() %>% 
  select(Date) %>% 
  distinct() %>% 
  count()


# Calculate highest and lowest biomass months 
# Highest and lowest (change arrange())
Sp_only %>% 
  group_by(months, month, year, Season) %>% 
  summarise(monthlyMean = mean(meanCells, na.rm = TRUE), 
            monthlyN = n(),
            monthlySD = sd(meanCells, na.rm = TRUE), 
            monthlySE = sd(meanCells, na.rm = TRUE)/sqrt(n())) %>% 
  arrange(desc(monthlyMean)) %>% 
  view()


dailyDesc %>% 
  arrange(desc(total_biomass)) %>% 
  select(total_biomass, everything())



#### Richness ####
# Highest and lowest (change arrange())
dailyDesc %>% 
  group_by(months, month, year, Season) %>% 
  summarise(monthlyRichness = mean(S, na.rm = TRUE), 
            monthlyRichnessN = n(),
            monthlyRichnessSD = sd(S, na.rm = TRUE), 
            monthlyRichnessSE = sd(S, na.rm = TRUE)/sqrt(n())) %>% 
  arrange(desc(-monthlyRichness)) %>% 
  view()


# July
dailyDesc_jul <- dailyDesc  %>% 
  filter(months == "July")%>% 
  group_by(months, month, year, Season) %>% 
  summarise(monthlyRichness = mean(S, na.rm = TRUE), 
            monthlyRichnessN = n(),
            monthlyRichnessSD = sd(S, na.rm = TRUE), 
            monthlyRichnessSE = sd(S, na.rm = TRUE)/sqrt(n())) %>% 
  arrange(desc(-monthlyRichness))



# test using Kruskal
kruskal.test(S ~ year, data = dailyDesc_jul)

# Pairwise tests
# ties are present so did not work
pairwise.wilcox.test(dailyDesc_jul$S, dailyDesc_jul$year, p.adjust.method = "bonf")



# Posthoc using kruskal Dunn -> Works
posthoc.kruskal.dunn.test(dailyDesc_jul$S, dailyDesc_jul$year, dist = "Tukey", p.adjust.methods = "bonferroni")

# January
dailyDesc_jan <- dailyDesc  %>% 
  filter(months == "January")%>% 
  group_by(months, month, year, Season)

summarise(monthlyRichness = mean(S, na.rm = TRUE), 
            monthlyRichnessN = n(),
            monthlyRichnessSD = sd(S, na.rm = TRUE), 
            monthlyRichnessSE = sd(S, na.rm = TRUE)/sqrt(n())) %>% 
  arrange(desc(-monthlyRichness))



# test using Kruskal
kruskal.test(S ~ year, data = dailyDesc_jan)

# Pairwise tests
# ties are present so did not work
pairwise.wilcox.test(dailyDesc_jan$S, dailyDesc_jan$year, p.adjust.method = "bonf")



# Posthoc using kruskal Dunn -> Works
posthoc.kruskal.dunn.test(dailyDesc_jan$S, dailyDesc_jan$year, dist = "Tukey", p.adjust.methods = "bonferroni")


# April
dailyDesc_apr <- dailyDesc  %>% 
  filter(months == "April")%>% 
  group_by(months, month, year, Season)

summarise(monthlyRichness = mean(S, na.rm = TRUE), 
            monthlyRichnessN = n(),
            monthlyRichnessSD = sd(S, na.rm = TRUE), 
            monthlyRichnessSE = sd(S, na.rm = TRUE)/sqrt(n())) %>% 
  arrange(desc(-monthlyRichness))



# test using Kruskal
kruskal.test(S ~ year, data = dailyDesc_apr)

# Pairwise tests
# ties are present so did not work
pairwise.wilcox.test(dailyDesc_apr$S, dailyDesc_apr$year, p.adjust.method = "bonf")



# Posthoc using kruskal Dunn -> Works
posthoc.kruskal.dunn.test(dailyDesc_apr$S, dailyDesc_apr$year, dist = "Tukey", p.adjust.methods = "bonferroni")




##### Evenness #####
dailyDesc_jul_J <- dailyDesc %>%
  group_by(months, month, year, Season) %>% 
  summarise(monthlyEvenness = mean(J, na.rm = TRUE), 
            monthlyEvennessN = n(),
            monthlyEvennessD = sd(J, na.rm = TRUE), 
            monthlyEvennessSE = sd(J, na.rm = TRUE)/sqrt(n())) %>% 
  arrange(desc(-monthlyEvenness))

dailyDesc_jul_J %>% 
  filter(months == "July") %>% 
  select(monthlyEvenness, monthlyEvennessSE, everything()) %>% 
  arrange(desc(monthlyEvenness))

yJ <- dailyDesc %>% 
  group_by(months, month, year) %>% 
  summarise(me = mean(J, na.rm = TRUE))

# test using Kruskal
kruskal.test(J ~ year, data = dailyDesc)
# Pairwise tests
# ties are present so did not work
pairwise.wilcox.test(dailyDesc$J, dailyDesc$year, p.adjust.method = "bonf")

# shannon diversity

dailyDesc %>% 
  group_by(months, month, year, Season) %>% 
  summarise(monthlyshannon = mean(shannon, na.rm = TRUE), 
            monthlyshannonN = n(),
            monthlyshannonsD = sd(shannon, na.rm = TRUE), 
            monthlyshannonSE = sd(shannon, na.rm = TRUE)/sqrt(n())) %>% 
  arrange(desc(-monthlyshannon))


# test using Kruskal
kruskal.test(shannon ~ year, data = dailyDesc)

# Pairwise tests
# ties are present so did not work
pairwise.wilcox.test(dailyDesc$shannon, dailyDesc$year, p.adjust.method = "bonf")



#### dominant species ####
Sp_only %>% 
  group_by(months, month, year, Species) %>% 
  summarise(monthlyMean = mean(meanCells, na.rm = TRUE), 
            monthlyN = n(),
            monthlySD = sd(meanCells, na.rm = TRUE), 
            monthlySE = sd(meanCells, na.rm = TRUE)/sqrt(n())) %>% 
  arrange(desc(monthlyMean)) %>% 
  filter(months == "April") %>% 
  view()

feb_18 <- Sp_only %>% 
  filter(year == "2018") %>% 
  filter (months == "February") %>%
  group_by(Date, Species)

pairwise.wilcox.test(ap_18$meanCells, ap_18$Species, p.adjust.method = "bonf")


month.rel %>% 
  filter(Species %in% dsp$Species) %>% 
  arrange(desc(abun)) %>% 
  distinct() %>% 
  view()




Crtmfs <- month.rel %>% 
  filter(Sp_abb == "Crtmfs")


Crtmfs_YM <- pairwise.wilcox.test(Crtmfs$abun, Crtmfs$YEarMonth, p.adjust.method = "bonf")
Crtmfs_YM_pvalue <- Crtmfs_YM[["p.value"]]

Crtmfs_YM_pvalue

reorder(Crtmfs$months, Crtmfs$month)


#### phytoplankton classes #####

Sp_only %>% 
  filter(Classification == "Ciliate", months == "August")


Sp_only %>% 
  group_by(months, month, Classification) %>% 
  summarise(monthlyMean = mean(meanCells, na.rm = TRUE), 
            monthlyN = n(),
            monthlySD = sd(meanCells, na.rm = TRUE), 
            monthlySE = sd(meanCells, na.rm = TRUE)/sqrt(n())) %>%
  #filter(monthlySE != "NA") %>% 
  ggplot(., aes(x = reorder(months, month), y = monthlyMean, col = Classification)) +
   geom_point(size = 1) +
  #geom_line(size = 0.8) +
  geom_errorbar(aes(ymin = monthlyMean - monthlySE, ymax = monthlyMean + monthlySE), width=0.2) +
  #facet_wrap(~year, ncol = 1) +
  scale_y_log10()

ggplotly(Sp_only %>% 
  group_by(months, month, year, Season, Classification) %>% 
  summarise(monthlyMean = mean(meanCells, na.rm = TRUE)) %>% 
  ggplot(., aes(x = reorder(months, month), y = monthlyMean, fill = Classification)) +
  geom_bar(stat = "Identity", position = "fill", col = "Black") +
  facet_wrap(~year, ncol = 1) +
  xlab("Months") +
  ylab("Proportion monthly mean") + 
  labs(fill = "Phytoplankton class") +
  ggtitle("Comparing the proportion of mean monthly counts between phytoplankton 
          classes over three consecutive years") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5)))

Sp_only %>% 
  group_by(months, month, year, Season, Classification) %>% 
  summarise(monthlyMean = mean(meanCells, na.rm = TRUE)) %>% 
  filter(Classification != "Dinoflagellate") %>% 
  filter(Classification != "Diatom") %>%
  ggplot(., aes(x = reorder(months, month), y = monthlyMean, fill = Classification)) +
  geom_bar(stat = "Identity", position = "Dodge", col = "Black") +
  facet_wrap(~year, ncol = 1)

Sp_only %>% 
  filter(months == "November" & year == "2019") %>%
  group_by(Classification) %>% 
  count(n_distinct(Species))

Sp_only %>% 
  filter(months == "October" & year == "2019" & Classification == "Diatom") %>% 
  ungroup() %>% 
  select(Species) %>%
  distinct()




##### NMDS #####




##### Red Tide classes ####


# Count number of days each class was present for each month
are <- all_max_cells_day %>% 
  left_join(select(PS, Date, months, year, YEarMonth), by = c("Date", "months"), keep = FALSE) %>%
  filter(year != "2020") %>% 
  group_by(months, month, year, YEarMonth, FWC_mod) %>% 
  distinct() %>% 
  count() %>% 
  arrange(desc(n))

kruskal.test(n ~ months, data = are)

# pivot classes wider to individually compare
FWC_classes_wide <- are %>% 
  pivot_wider(names_from = "FWC_mod", values_from = "n", values_fill = list(n = 0))


# Test each class for overall sig dif
kruskal.test(`Very Low` ~ year, data = FWC_classes_wide)
kruskal.test(Normal ~ year, data = FWC_classes_wide)
kruskal.test(Medium ~ year, data = FWC_classes_wide)
kruskal.test(Low ~ year, data = FWC_classes_wide)
kruskal.test(High ~ year, data = FWC_classes_wide)



# pairwise for Normal
FWC_classes_wide %>% 
  ungroup() %>% 
  dplyr::select(Normal, year) %>% 
  dunn_test(Normal ~ year, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj))

# pairwise for low
FWC_classes_wide %>% 
  ungroup() %>% 
  dplyr::select(Low, year) %>% 
  dunn_test(Low ~ year, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj))

FWC_classes_wide %>% 
  ungroup() %>% 
  dplyr::select(`Very Low`, year) %>% 
  dunn_test(`Very Low` ~ year, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj))


posthoc.kruskal.dunn.test(FWC_classes_wide$Normal, FWC_classes_wide$year, dist = "Tukey", p.adjust.method = "bonferroni")

#### Resources ####

link <- PS %>% 
  dplyr::select(Date, year)

# Daily counts
daily_counts <- left_join(max_cells_day, Time_count, by = "Date") %>% 
  semi_join(link, by = "Date")

# Overall significance check
kruskal.test(count_times ~ months, data = daily_counts)

# pairwise check between months
count_diff <- daily_counts %>% 
  ungroup() %>% 
  dplyr::select(months, count_times) %>% 
  dunn_test(count_times ~ months, p.adjust.method = "bonferroni")
# plot pairwise tests to visualise significant month partners
ggplot(data = count_diff, aes(x = group1, y = group2, fill = p.adj)) + 
  geom_tile(col = "black") +
  geom_text(aes(label = round(p.adj, digits = 2))) +
  coord_flip()


ggplotly(ggplot(data = count_diff, aes(x = group1, y = group2, col = p.adj)) +
  geom_point(aes(size = 1-p.adj)) +
  coord_flip())


count_diff %>% 
  group_by(group1, p.adj.signif) %>% 
  count() %>% 
  arrange(desc(n))

# Correlation between sampling number and biomass 
count_cells_cor <- daily_counts %>% 
  ungroup() %>% 
  select(count_times, totalCells) %>% 
  mutate(count_times = log10(count_times), 
         totalCells = log10(totalCells)) %>% 
  cor_test(count_times, totalCells, method = "spearman")



```


```{r Chapter 3}
#### significant difference between biomass in different sites  ####

# calculate descriptive stats
Sp.only_filter %>% 
  group_by(Site, months) %>% 
  summarise(mean_cells = mean(meanCells, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(meanCells, na.rm = TRUE), 
            se_cells = sd(meanCells, na.rm = TRUE)/sqrt(n())) %>% 
  view()

### Total significance? 

Sp.only_filter %>% 
  group_by(Date, months, Site) %>% 
  summarise(mean_cells = mean(meanCells, na.rm = TRUE)) %>% 
  ungroup() %>% 
  select(Site, mean_cells) %>% 
  dunn_test(mean_cells ~ Site, p.adjust.method = "bonferroni")


# Feb signif
Sp.only_filter %>% 
  group_by(Date, months, Site) %>% 
  filter(months == "February") %>% 
  summarise(mean_cells = mean(meanCells, na.rm = TRUE)) %>% 
  ungroup() %>% 
  select(Site, mean_cells) %>% 
  dunn_test(mean_cells ~ Site, p.adjust.method = "bonferroni")


# March signif
Sp.only_filter %>% 
  group_by(Date, months, Site) %>% 
  filter(months == "March") %>% 
  summarise(mean_cells = mean(meanCells, na.rm = TRUE)) %>% 
  ungroup() %>% 
  select(Site, mean_cells) %>% 
  dunn_test(mean_cells ~ Site, p.adjust.method = "bonferroni")

# April signif
Sp.only_filter %>% 
  group_by(Date, months, Site) %>% 
  filter(months == "April") %>% 
  summarise(mean_cells = mean(meanCells, na.rm = TRUE)) %>% 
  ungroup() %>% 
  select(Site, mean_cells) %>% 
  dunn_test(mean_cells ~ Site, p.adjust.method = "bonferroni")



## richness sig dif ######

dailydesc_filter %>% 
  view()

# Total sig dif
dailydesc_filter %>% 
  select(Site, S) %>% 
  dunn_test(S ~ Site, p.adjust.method = "bonferroni")


# Feb

dailydesc_filter %>% 
  filter(months == "February") %>% 
  select(Site, S) %>% 
  dunn_test(S ~ Site, p.adjust.method = "bonferroni")

# March 
dailydesc_filter %>% 
  filter(months == "March") %>% 
  select(Site, S) %>% 
  dunn_test(S ~ Site, p.adjust.method = "bonferroni")

# April
dailydesc_filter %>% 
  filter(months == "April") %>% 
  select(Site, S) %>% 
  dunn_test(S ~ Site, p.adjust.method = "bonferroni")






## evenness sig dif ####

# Total sig dif
dailydesc_filter %>% 
  select(Site, J) %>% 
  dunn_test(J ~ Site, p.adjust.method = "bonferroni")

# Feb
dailydesc_filter %>% 
  filter(months == "April") %>% 
  select(Site, J) %>% 
  dunn_test(J ~ Site, p.adjust.method = "bonferroni")

# March 
dailydesc_filter %>% 
  filter(months == "March") %>% 
  select(Site, J) %>% 
  dunn_test(J ~ Site, p.adjust.method = "bonferroni")

# April
dailydesc_filter %>% 
  filter(months == "April") %>% 
  select(Site, J) %>% 
  dunn_test(J ~ Site, p.adjust.method = "bonferroni")

## diversity sig dif #####

# Total sig dif
dailydesc_filter %>% 
  select(Site, shannon) %>% 
  dunn_test(shannon ~ Site, p.adjust.method = "bonferroni")

# Feb
dailydesc_filter %>% 
  filter(months == "February") %>% 
  select(Site, shannon) %>% 
  dunn_test(shannon ~ Site, p.adjust.method = "bonferroni")

# March
dailydesc_filter %>% 
  filter(months == "March") %>% 
  select(Site, shannon) %>% 
  dunn_test(shannon ~ Site, p.adjust.method = "bonferroni")

# April
dailydesc_filter %>% 
  filter(months == "April") %>% 
  select(Site, shannon) %>% 
  dunn_test(shannon ~ Site, p.adjust.method = "bonferroni")



#### Species change betwen sites #####

## P. micans 

# total biommass for species over sites
P.m_only <- Sp.only_filter %>% 
  filter(Species == "Prorocentrum micans") %>% 
  ungroup() 

P.m_only %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")

# Monthly
# Feb

# descriptive statistics ( used to justify p-values)
P.m_only %>% 
  filter(months == "February") %>% 
  group_by(Site) %>% 
  summarise(me = mean(meanCells, na.rm = TRUE), 
            se = sd(meanCells, na.rm = TRUE)/sqrt(n())) 

# sig dif
P.m_only %>% 
  filter(months == "February") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")

# March

# sig dif
P.m_only %>% 
  filter(months == "March") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")

# April
# sig dif
P.m_only %>% 
  filter(months == "April") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")





## L. polyedra

# total biommass for species over sites
L.p_only <- Sp.only_filter %>% 
  filter(Species == "Lingulodinium polyedra") %>% 
  ungroup() 

# Feb
# sig dif
L.p_only %>% 
  filter(months == "February") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")

# March
# sig dif
L.p_only %>% 
  filter(months == "March") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")

# April
# sig dif
L.p_only %>% 
  filter(months == "April") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")



## G. polygramma

# total biommass for species over sites
G.p_only <- Sp.only_filter %>% 
  filter(Species == "Gonyaulax polygramma") %>% 
  ungroup() 


# Feb
# sig dif
G.p_only %>% 
  filter(months == "February") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")

# March
# sig dif
G.p_only %>% 
  filter(months == "March") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")



# April
# sig dif
G.p_only %>% 
  filter(months == "April") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")





#### Which species are significantly reduced between the PS and ADf? #####

# Pivot species wide
# calculate descriptive on monthly level between sites, for each species
# plot
# decide which species to extract
# do sig dif for top two

# Which species have biggest range between sites?


Sp.only_filter %>% 
  ungroup() %>% 
  select(Date, months, Site, Species, meanCells) %>% 
  pivot_wider(names_from = Site, values_from = meanCells, values_fill = list(meanCells = 0)) %>% 
  mutate(differ = `Primary sump` - `After Drumfilter`) %>% 
  arrange(desc(differ)) %>% 
  view()



Sp.only_filter %>% 
  ungroup() %>% 
  select(Date, months, Site, Species, meanCells) %>% 
  pivot_wider(names_from = Species, values_from = meanCells, values_fill = list(meanCells = 0)) %>% 
  view()




trans <- Sp.only_filter %>% 
  mutate(meanCells = log10(meanCells))

all_sp_feb <- trans %>% 
  ungroup() %>% 
  mutate(Sp_site = paste(Species, Site, sep = "_")) %>% 
  filter(months == "February") %>% 
  select(meanCells, Sp_site) %>% 
  dunn_test(meanCells ~ Sp_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

feb_sig <- trans %>% 
  ungroup() %>% 
  mutate(Sp_site = paste(Species, Site, sep = "_")) %>% 
  filter(months == "February") %>% 
  select(meanCells, Sp_site) %>% 
  dunn_test(meanCells ~ Sp_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

march_sig <- trans %>% 
  ungroup() %>% 
  mutate(Sp_site = paste(Species, Site, sep = "_")) %>% 
  filter(months == "March") %>% 
  select(meanCells, Sp_site) %>% 
  dunn_test(meanCells ~ Sp_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

apr_sig <- trans %>% 
  ungroup() %>% 
  mutate(Sp_site = paste(Species, Site, sep = "_")) %>% 
  filter(months == "April") %>% 
  select(meanCells, Sp_site) %>% 
  dunn_test(meanCells ~ Sp_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")


# all_sp_feb %>%
#   filter(substr(group1, 1, 10) == substr(group2, 1, 10))




pairwise.wilcox.test(all_sp_feb$meanCells, all_sp_feb$Species, p.adjust.method = "bonf")


## Classification

cl <- Sp.only_filter %>% 
  mutate(meanCells = log10(meanCells))

cl %>% 
  ungroup() %>% 
  mutate(cl_site = paste(Classification, Site, sep = "_")) %>% 
  # filter(months == "February") %>% 
  select(meanCells, cl_site) %>% 
  dunn_test(meanCells ~ cl_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")


cl.feb_sig <- cl %>% 
  ungroup() %>% 
  mutate(cl_site = paste(Classification, Site, sep = "_")) %>% 
  filter(months == "February") %>% 
  select(meanCells, cl_site) %>% 
  dunn_test(meanCells ~ cl_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

cl.march_sig <- cl %>% 
  ungroup() %>% 
  mutate(cl_site = paste(Species, Site, sep = "_")) %>% 
  filter(months == "March") %>% 
  select(meanCells, cl_site) %>% 
  dunn_test(meanCells ~ cl_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

cl.apr_sig <- cl %>% 
  ungroup() %>% 
  mutate(cl_site = paste(Species, Site, sep = "_")) %>% 
  filter(months == "April") %>% 
  select(meanCells, cl_site) %>% 
  dunn_test(meanCells ~ cl_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

```

```{r Deeper look at all sites comparisons for chapter 3}

compare_sites_days <- Sp.only_filter %>% 
  group_by(Date, Site) %>% 
  mutate(meanCells = log10(meanCells)) %>% 
  get_summary_stats(meanCells, type = "mean_se")

ggplot(data = compare_sites_days, aes(x = Date, y = mean, col = Site)) +
  geom_point() +
  geom_errorbar(aes(ymax = mean + se, ymin = mean - se))


# This compare all counts for sites, and not only during the same days that all sites were sampled
#  so might not be a good idea to use
df %>% 
  filter(Location != "NA") %>% 
  filter(Location != "I'm not sure which site this two is") %>% 
  group_by(Date, months, month, Species, Classification, Site, Location) %>% 
  summarise(meanC = mean(log10(totalCells), na.rm = TRUE)) %>% 
  filter(months == "April") %>% 
  ungroup() %>% 
  select(Date, meanC, Location) %>% 
  dunn_test(meanC ~ Location, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

# Dates where Bergsig was sampled
bs <- df %>% 
  filter(Location == "Bergsig farm")
 
# Plot these groups
df %>% 
  filter(Date %in% bs$Date) %>%
  filter(Location == "Bergsig farm" | Location == "Hatchery farm" | 
           Location == "Incoming seawater" | Location == "Seaview farm") %>%
  mutate(mc = log10(Cells.L)) %>% 
  ggplot(., aes(x = Location, y = mc)) +
  geom_boxplot(outlier.shape = NA)
  

# Check for significance
df %>% 
  filter(Date %in% bs$Date) %>%
  filter(Location == "Bergsig farm" | Location == "Hatchery farm" | 
           Location == "Incoming seawater" | Location == "Seaview farm") %>%
  mutate(mc = log10(Cells.L)) %>% 
  group_by(Date, Location) %>% 
  summarise(mc = mean(mc, na.rm = TRUE)) %>% 
  # select(mc, Location) %>% 
  dunn_test(mc ~ Location, p.adjust.method = "bonferroni") %>% 
  view()
  
  
```


```{r All years summarised to months CORRECT METHOD}


# All years summarised to 12 months (Shows good grouping)

wide_avg_months <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(months, Sp_abb) %>% 
  summarise(averageDens = log10(mean(meanCells, na.rm = TRUE))) %>% 
  semi_join(., mse, by = "Sp_abb") %>% 
  ungroup() %>% 
  pivot_wider(names_from = "Sp_abb", values_from = "averageDens", 
              values_fill = list(averageDens = 0))  %>%
  remove_rownames %>% 
  column_to_rownames(var= "months")


wide_avg_months_relative <- make_relative(as.matrix(wide_avg_months))

NMDS_avg_months <- metaMDS(wide_avg_months_relative, k = 2, autotransform = FALSE, trymax = 100)

NMDS_avg_months

plot(NMDS_avg_months)
ordiplot(NMDS_avg_months,type="n")
orditorp(NMDS_avg_months,display="species",col="red",air=0.01)
orditorp(NMDS_avg_months,display="sites",cex=1.25,air=0.01)

## Convert results to use in ggplot2
av_months_site_scores <- as.data.frame(scores(NMDS_avg_months, display = "sites")) %>% 
  rownames_to_column(var = "label") %>% 
  mutate(level = as.factor("avg_months"))


av_months_species <- as.data.frame(scores(NMDS_avg_months, display = "species")) %>% 
  rownames_to_column(var = "label") %>% 
  mutate(level = as.factor("Species"))


# Might not be nec  
av_months_site_sp <- bind_rows(av_months_site_scores, av_months_species)

# Plot ggplot
ggplot(data = av_months_species, aes(x = NMDS1, y = NMDS2, col = level, label = label)) +
  geom_text() +
  geom_text(data = av_months_site_scores, aes(x = NMDS1, y = NMDS2, col = level, label = label), size = 5) +
  scale_color_manual(values = c("black", "red")) +
  theme_classic() +
  theme(legend.position = "none")

## ANOSIM on results




```


```{r ANOSIM testing}
# Compare biomass between months and years using ANOSIM
# Two way crossed method
# Summarise by year first and compare
# Summarise by months and compare

# Year

# All years summarised to 12 months (Shows good grouping)

# anosim of months

date_year <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(Date, year, Sp_abb) %>% 
  summarise(averageDens = log10(mean(meanCells, na.rm = TRUE))) %>% 
  semi_join(., mse, by = "Sp_abb") %>% 
  ungroup() %>% 
  pivot_wider(names_from = "Sp_abb", values_from = "averageDens", 
              values_fill = list(averageDens = 0))

# create matrix
date_year_relative <- as.matrix(
    date_year[,3:ncol(date_year)]
    )

# Correct
ano_year <- anosim(date_year_relative, 
                     date_year$year,
                     distance="bray", 
                     permutations = 999)
ano_year

# # Simper years
# simper_year <- simper(date_year_relative, 
#                      date_year$year,
#                      permutations = 999)
# simper_year
# 
# simper_year_summ <- summary(simper_year)



# # Simper months
# simper_months <- simper(wide_avg_months_relative_t, 
#                      wide_avg_months_t$months,
#                      permutations = 999)
# simper_months
# 
# simper_months_summ <- summary(simper_months)


## anosim of months

date_month <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(Date, months, Sp_abb) %>% 
  summarise(averageDens = log10(mean(meanCells, na.rm = TRUE))) %>% 
  semi_join(., mse, by = "Sp_abb") %>% 
  ungroup() %>% 
  pivot_wider(names_from = "Sp_abb", values_from = "averageDens", 
              values_fill = list(averageDens = 0))

# create matrix
date_month_relative <- as.matrix(
    date_month[,3:ncol(date_month)]
    )

# Correct
ano_months <- anosim(date_month_relative, 
                     date_month$months,
                     distance="bray", 
                     permutations = 999)
ano_months



```



```{r}
knitr::knit_exit()
```

####### This is scrap work #######

```{r NMDS all years sep}
# Just 2019

wide_2019 <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  filter(year == "2019") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(months, Sp_abb) %>% 
  summarise(averageDens = log10(mean(meanCells, na.rm = TRUE))) %>% 
  semi_join(., mse, by = "Sp_abb") %>% 
  ungroup() %>% 
  pivot_wider(names_from = "Sp_abb", values_from = "averageDens", 
              values_fill = list(averageDens = 0))  %>%
  remove_rownames %>% 
  column_to_rownames(var= "months")


wide_2019_relative <- make_relative(as.matrix(wide_2019))

NMDS_2019 <- metaMDS(wide_2019_relative, k = 3, autotransform = FALSE, trymax = 100)


NMDS_2019

plot(NMDS_2019)
ordiplot(NMDS_2019,type="n")
orditorp(NMDS_2019,display="species",col="red",air=0.01)
orditorp(NMDS_2019,display="sites",cex=1.25,air=0.01)






# Just 2018

wide_2018 <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  filter(year == "2018") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(months, Sp_abb) %>% 
  summarise(averageDens = log10(mean(meanCells, na.rm = TRUE))) %>% 
  semi_join(., mse, by = "Sp_abb") %>% 
  ungroup() %>% 
  pivot_wider(names_from = "Sp_abb", values_from = "averageDens", 
              values_fill = list(averageDens = 0))  %>%
  remove_rownames %>% 
  column_to_rownames(var= "months")


wide_2018_relative <- make_relative(as.matrix(wide_2018))

NMDS_2018 <- metaMDS(wide_2018_relative, k = 3, autotransform = FALSE, trymax = 100)


NMDS_2018

plot(NMDS_2018)
ordiplot(NMDS_2018,type="n")
orditorp(NMDS_2018,display="species",col="red",air=0.01)
orditorp(NMDS_2018,display="sites",cex=1.25,air=0.01)


# Just 2017

wide_2017 <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  filter(year == "2017") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(months, Sp_abb) %>% 
  summarise(averageDens = log10(mean(meanCells, na.rm = TRUE))) %>% 
  semi_join(., mse, by = "Sp_abb") %>% 
  ungroup() %>% 
  pivot_wider(names_from = "Sp_abb", values_from = "averageDens", 
              values_fill = list(averageDens = 0))  %>%
  remove_rownames %>% 
  column_to_rownames(var= "months")


wide_2017_relative <- make_relative(as.matrix(wide_2017))

NMDS_2017 <- metaMDS(wide_2017_relative, k = 3, autotransform = FALSE, trymax = 100)


NMDS_2017

plot(NMDS_2017)
ordiplot(NMDS_2017,type="n")
orditorp(NMDS_2017,display="species",col="red",air=0.01)
orditorp(NMDS_2017,display="sites",cex=1.25,air=0.01)
```


```{r adonis testing #1}

# Summarise species to monthly avg
# pivot wider to prep for matrix
year_month <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(months, year, Sp_abb) %>% 
  summarise(averageDens = log10(mean(meanCells, na.rm = TRUE))) %>% 
  semi_join(., mse, by = "Sp_abb") %>% 
  ungroup() %>% 
  pivot_wider(names_from = "Sp_abb", values_from = "averageDens", 
              values_fill = list(averageDens = 0))

# create grouping df
year_month_groups <- year_month %>% 
  select(months, year)

year_month_groups$months <- as.factor(year_month_groups$months)
class(year_month_groups$months )

# create dissim matrix
year_month_mat_relative <- vegdist(as.matrix(year_month  %>%
  select(-c(months, year))), method = "bray")




# adonis for years stratified by months
adonis(year_month_mat_relative ~ months, 
       data = year_month_groups, 
       method = "bray", 
       perm = 999, strata = year_month_groups$year)

betadisper(year_month_mat_relative, year_month_groups$year)

# adonis for months stratified by years
adonis(year_month_mat_relative ~ months, 
       data = year_month_groups, 
       method = "bray", 
       perm = 999, strata = year_month_groups$year)

bt <- betadisper(year_month_mat_relative, year_month_groups$months)



summary(with(year_month_groups, anosim(year_month_mat_relative, months, strata = year)))

```


```{r pairwise adonis testing}
library(cluster)
library(pairwiseAdonis)

pairwise.adonis(year_month_mat_relative, year_month_groups$months, perm = 999,)

pairwise.adonis2(year_month_mat_relative ~ months, 
                 data = year_month_groups, 
                 perm = 999, strata = year)



```



```{r adonis testing #2 Dates include}

# Summarise species to monthly avg
# pivot wider to prep for matrix
year_month <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(Date, months, year, Sp_abb) %>% 
  summarise(averageDens = log10(mean(meanCells, na.rm = TRUE))) %>% 
  semi_join(., mse, by = "Sp_abb") %>% 
  ungroup() %>% 
  pivot_wider(names_from = "Sp_abb", values_from = "averageDens", 
              values_fill = list(averageDens = 0))

# create grouping df
year_month_groups <- year_month %>% 
  select(months, year)

# create dissim matrix
year_month_mat_relative <- vegdist(as.matrix(year_month  %>%
  select(-c(months, year, Date))), method = "bray")

# adonis using months and year
adonis(year_month_mat_relative ~ year, 
       data = year_month_groups, 
       method = "bray", 
       perm = 999)

betadisper(year_month_mat_relative, year_month_groups$months)

```

```{r March April only}

# Summarise species to monthly avg
# pivot wider to prep for matrix
year_month <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  filter(months %in% c("March", "April"), year == "2019") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(Date, months, year, Sp_abb) %>% 
  summarise(averageDens = log10(mean(meanCells, na.rm = TRUE))) %>% 
  semi_join(., mse, by = "Sp_abb") %>% 
  ungroup() %>% 
  pivot_wider(names_from = "Sp_abb", values_from = "averageDens", 
              values_fill = list(averageDens = 0))

# create grouping df
year_month_groups <- year_month %>% 
  select(months, year)

# create dissim matrix
year_month_mat_relative <- vegdist(as.matrix(year_month  %>%
  select(-c(Date, months, year))), method = "bray")

# adonis using months and year
adonis(year_month_mat_relative ~ months, 
       data = year_month_groups, 
       method = "bray", 
       perm = 999)

betadisper(year_month_mat_relative, year_month_groups$months)

```


```{r Different NMDS based on all months and years used (YEarMonth)}

# YEarMonth

wide_all_months <- Sp_only %>%
  ungroup() %>% 
  filter(Species != "Diatom") %>% 
  mutate(Sp_abb = abbreviate(Species, 5, strict = FALSE)) %>% 
  group_by(YEarMonth, Sp_abb) %>% 
  summarise(averageDens = log10(mean(meanCells, na.rm = TRUE))) %>% 
  semi_join(., mse, by = "Sp_abb") %>% 
  ungroup() %>% 
  pivot_wider(names_from = "Sp_abb", values_from = "averageDens", 
              values_fill = list(averageDens = 0))  %>%
  remove_rownames %>% 
  column_to_rownames(var= "YEarMonth")


wide_all_months_relative <- make_relative(as.matrix(wide_all_months))

NMDStestmonth_test <- metaMDS(wide_all_months_relative, k = 3, autotransform = FALSE, trymax = 100)


NMDStestmonth_test

plot(NMDStestmonth_test)
ordiplot(NMDStestmonth_test,type="n")
orditorp(NMDStestmonth_test,display="species",col="red",air=0.01)
orditorp(NMDStestmonth_test,display="sites",cex=1.25,air=0.01)

```








