---
title: "Fixing chapter 3"
author: "Tim Ponton"
date: "26/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chapter 3 setup


```{r, include=FALSE, warning=FALSE}

# run  lines from 'Building Chp2' until before subsetting PS only 

## load data
# size classes of dominant species 
sp_sizes <- read.csv("Updated data from April 2020/Dominant sizes.csv", stringsAsFactors = FALSE)

# subset dates for when both Ps and ADF were sampled ----------------------

df <- read.csv("Oct 2020/2017.2019.OR/written_df_Oct.csv")



# fix date
df$Date <- as.Date(df$Date, "%Y/%m/%d")

# add month and year columns 
df <- df %>% 
  mutate(months = months(Date), month = month(Date), year = year(Date), YEarMonth = as.yearmon(paste(year, month), "%Y %m"))

# merge date and times and coerce to proper format 
df$dateTime <- as.POSIXct(paste(df$Date, df$Time), format = "%Y-%m-%d %H:%M")

# coerce year column as factor
df$year <- as.factor(df$year)

correct_dates <- df %>% 
  filter(Date >= "2019-02-01" & Date <= "2019-04-30") %>%
  filter(Site %in% c("Primary sump", "After Drumfilter")) %>% 
  select(Date, Time, Site, Correct.Original) %>%
  group_by(Date, Site) %>% 
  summarise(sumC = sum(Correct.Original, na.rm = TRUE)) %>% 
  # group_by(Date, Site) %>% 
  # summarise(meanC = mean(sumC, na.rm = TRUE)) %>% 
  pivot_wider(names_from = Site, values_from = sumC, 
              values_fil = list(sumC = 0)) %>%
  filter(`After Drumfilter` != "NA", `After Drumfilter` != 0)



# create a df to use as a basis
ps_adf <- df %>% 
  filter(Date >= "2019-02-01" & Date <= "2019-04-30") %>%
  filter(Date %in% correct_dates$Date) %>% 
  filter(Site %in% c("After Drumfilter", "Primary sump")) %>% 
  #filter(Site %in% c("After Drumfilter", "Primary sump")) %>% 
  filter(#Species != "Diatom", 
         #Classification != "Various", 
         Classification != "Ciliate", 
         Classification != "Spirotrichea", 
         Classification != "Litostomatea")

# relationship between cell count and cells filtered between sites. 
df %>% 
  filter(Date >= "2019-02-01" & Date <= "2019-04-30") %>%
  filter(all(c("After Drumfilter", "Primary sump") %in% Site), Correct.Original != 0) %>% 
  filter(Site %in% c("After Drumfilter", "Primary sump")) %>% 
  filter(Species != "Diatom", 
         #Classification != "Various", 
         Classification != "Ciliate", 
         Classification != "Spirotrichea", 
         Classification != "Litostomatea") %>%
  group_by(Date, Time, Site, months, month, YEarMonth, year) %>% 
  summarise(sumC = sum(Correct.Original, na.rm = TRUE)) %>% 
  pivot_wider(names_from = Site, values_from = sumC, 
              values_fill = list(meanC = 0)) %>% 
  mutate(delta = `Primary sump` - `After Drumfilter`) %>% 
  filter(delta != "NA", 
         delta < 28140000, 
         delta > 0) %>% 
  ggplot(., aes(x = `Primary sump`, y = delta)) +
  geom_point(aes(col = months)) +
  geom_smooth(method = lm) +
  scale_x_log10() +
  scale_y_log10()
  
  
  
  group_by(Date, Site, months, month, YEarMonth, year) %>% 
  summarise(meanC = mean(sumC, na.rm = TRUE)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = Site, values_from = meanC, 
              values_fill = list(meanC = 0)) %>% 
  filter(`After Drumfilter` != 0) %>% 
  mutate(delta = `Primary sump` - `After Drumfilter`) %>%
  filter(delta >= 0, 
         delta < 2000000) %>% 
  ggplot(., aes(x = `Primary sump`, y = delta)) +
  geom_point(aes(col = months))




# correct the order of sites (PS before ADf)
ps_adf$Site <- as.factor(ps_adf$Site)
ps_adf$Site <-  factor(ps_adf$Site, 
                       levels = c("Primary sump", "After Drumfilter"))


# # correct levels of FWC_mod classes
# ps_adf$FWC_mod <- as.factor(ps_adf$FWC_mod)
# ps_adf$FWC_mod <-  factor(ps_adf$FWC_mod, 
#                    levels = c("High","Medium", "Low", "Very Low", "Normal"))



# Daily metrics of different sites ----------------------------------------

## calculate biomass evennes richness diversity per day/ week for each site
# average counts for each species per day
Sp.only_filter <- ps_adf %>% 
  group_by(Date, Site, Species, Classification, months, month, year) %>% 
  summarise(meanCells = mean(Correct.Original, na.rm = TRUE)) %>% 
  filter(Classification != "Various", 
         Species != "Diatom")

# total biomass per day (all species added together per day)


total_sp_filter <- ps_adf %>% 
  group_by(Date, Site, Time, months, month, year) %>% 
  summarise(sumC = sum(Correct.Original, na.rm = TRUE)) %>% 
  group_by(Date, Site, months, month, year) %>% 
  summarise(total_biomass = mean(sumC, na.rm = TRUE)) %>% 
  ungroup()



# richness
richness_filter <- Sp.only_filter %>% 
  filter(Classification != "Various") %>% 
  group_by(Date, Site) %>% 
  summarise(S = n_distinct(Species))


# diversity
# pivot species wider
div_filter <- Sp.only_filter %>% 
  ungroup() %>% 
  select(Date, Site, Species, meanCells) %>% 
  pivot_wider(names_from = Species, values_from = meanCells, 
              values_fill = list(meanCells = 0))

# create group
group_filter <- div_filter %>% 
  select(Date, Site)

# diversity for each day, and site
group_filter <- group_filter %>% 
  mutate(shannon2 = diversity(div_filter[, 3:ncol(div_filter)], "shannon", base = 2),
       shannon = diversity(div_filter[, 3:ncol(div_filter)], "shannon"),
       simpson = diversity(div_filter[, 3:ncol(div_filter)], "simpson"), 
       Inv_simpson = diversity(div_filter[, 3:ncol(div_filter)], "inv"))


# Join all metrics

dailydesc_filter <- left_join(total_sp_filter, group_filter, by = c("Date", "Site")) %>% 
  left_join(., richness_filter, by = c("Date", "Site"))


# calculate evenness
dailydesc_filter <- dailydesc_filter %>% 
  mutate(J2 = shannon2/log(S), 
       J = shannon/log(S))



# Comparing biomass at different points on farm  --------------------------------------------------------

# subset specific day when many sites had been sampled (2019-02-26)
## Filter unknown sites

# codecounts are filtered for all sampels after 12pm (afternoon)
# mutated time period to indicae when sampels were taken 
pos <- df %>% 
  filter(Date == "2019-02-26") %>% 
  filter(Site != "Unknown") %>% 
  # filter(CodeCount >= "3518" & CodeCount <= "3550") %>% 
  mutate(`Day Time period` = ifelse(Time %in% c("01:00", "03:00", "05:00", 
                                    "06:00", "07:45", "09:30", "10:15", "10:45"), 
                                    "Morning", "Afternoon"))
  
# Fix order of time period samples
pos$`Day Time period` <- as.factor(pos$`Day Time period`)
pos$`Day Time period` <-factor(pos$`Day Time period`, levels = c("Morning", "Afternoon"))

# fix order of Locations
pos$Location <- factor(pos$Location, levels = c("Incoming seawater", "Seaview farm", "Hatchery farm", "Bergsig farm"))

# Ind species fluctuations ------------------------------------------------

# daily means
# pivot sites wider
# calculate Ps minus ADf
sp_site_diff_daily <- Sp.only_filter %>% 
  pivot_wider(names_from = Site, values_from = meanCells, 
              values_fill = list(meanCells = 0)) %>% 
  mutate(site.Diff = `Primary sump` - `After Drumfilter`)


# pick top n species 
top_species <- Sp.only_filter %>% 
  group_by(Species, Classification) %>% 
  summarise(Sp_average = mean(meanCells, na.rm = TRUE)) %>% 
  arrange(desc(Sp_average)) %>% 
  ungroup() %>% 
  top_n(3) %>% 
  ungroup()


# filter top n species
sp_site_diff_daily <- sp_site_diff_daily %>% 
  filter(Species %in% top_species$Species)


# Average species to monthly means
# pivot sites wider
# calculate Ps minus ADf
sp_site_diff_monthly <- Sp.only_filter %>% 
  group_by(Site, months, month, Species, Classification) %>% 
  summarise(monthly.mean = mean(meanCells, na.rm = TRUE)) %>% 
  pivot_wider(names_from = Site, values_from = monthly.mean, 
              values_fill = list(monthly.mean = 0)) %>% 
  mutate(site.Diff = `Primary sump` - `After Drumfilter`)

# pick top n species 
top_species <- Sp.only_filter %>% 
  group_by(Species, Classification) %>% 
  summarise(Sp_average = mean(meanCells, na.rm = TRUE)) %>% 
  arrange(desc(Sp_average)) %>% 
  ungroup() %>% 
  top_n(3) %>% 
  ungroup()

# calculate mean size class
sp_sizes <- sp_sizes %>% 
  group_by(Species) %>% 
  mutate(mean_length = mean(min_length:max_length, na.rm = TRUE))

top_species <- top_species %>% 
  left_join(sp_sizes, by = "Species")


site_size <- Sp.only_filter %>% 
  group_by(Site, months, month, Species, Classification) %>% 
  #summarise(monthly.mean = mean(meanCells, na.rm = TRUE)) %>% 
  filter(Species %in% top_species$Species) %>% 
  left_join(top_species, by = "Species") %>% 
  ungroup()
  








# NMDS if sites influence species biomass --------------------------------








```




## Chapter 3 plots


```{r, warning=FALSE}


####### Chapter 3 Filters ################  


## PHYTOPLANKTON FLUCTUATIONS BETWEEN SITES --------------------------------



# summarise down to monthly measurements to compare sites [boxplot graph]

#'* Graphs for Aim 1a -------------*

# DO NOT USE 
# biomass
# ggplot(data = dailydesc_filter, aes(x = reorder(months, month), y = total_biomass, fill = Site)) +
#   geom_boxplot() +
#   xlab("Months") +
#   ylab("Cells/L") + 
#   labs(fill = "Site") +
#   ggtitle("Compare the difference in biomass of phytoplankton between the two sites, for three consecutive months") +
#   theme_classic() +
#   theme(plot.title = element_text(hjust = 0.5))

# Line version
ggplot(data = dailydesc_filter, aes(x = Date, y = total_biomass, col = Site)) +
  geom_line(size = 1) +
  facet_wrap(~reorder(months, month), ncol = 1, scales = "free")


# Point with errorbar version
Sp.only_filter %>% 
  mutate(YEarMonth = as.yearmon(paste(year, month), "%Y %m")) %>% 
  group_by(months, month, year, YEarMonth, Site) %>% 
  summarise(mean_cells = mean(meanCells, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(meanCells, na.rm = TRUE), 
            se_cells = sd(meanCells, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = mean_cells, col = Site, group = Site)) +
  geom_point() +
#  geom_line() +
  geom_errorbar(aes(ymin = mean_cells - se_cells, ymax = mean_cells + se_cells), width=0.2) +
  xlab("Months") +
  ylab("Cells/L") + 
  labs(fill = "Site") +
#  ggtitle("") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

total_sp_filter %>% 
  mutate(YEarMonth = as.yearmon(paste(year, month), "%Y %m")) %>% 
  group_by(months, month, year, YEarMonth, Site) %>% 
  summarise(mean_cells = mean(total_biomass, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(total_biomass, na.rm = TRUE), 
            se_cells = sd(total_biomass, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = mean_cells, col = Site, group = Site)) +
  geom_point() +
#  geom_line() +
  geom_errorbar(aes(ymin = mean_cells - se_cells, ymax = mean_cells + se_cells), width=0.2) +
  xlab("Months") +
  ylab("Cells/L") + 
  labs(fill = "Site") +
#  ggtitle("") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))


## Point errorbars can be done for the metrics  too if necessary ##

# richness
ggplot(data = dailydesc_filter, aes(x = reorder(months, month), y = S, fill = Site)) +
  geom_boxplot() +
  xlab("Months") +
  ylab("Number of species") + 
  labs(fill = "Site") +
  ggtitle("Compare the difference in species richness of phytoplankton between 
          the two sites, for three consecutive months of 2019") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

# evenness
ggplot(data = dailydesc_filter, aes(x = reorder(months, month), y = J, fill = Site)) +
  geom_boxplot() +
  xlab("Months") +
  ylab("Pielou's (J') Evenness") + 
  labs(fill = "Site") +
  ggtitle("Compare the difference in species evenness (J') of phytoplankton between 
          the two sites, for three consecutive months of 2019") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

# diversity
ggplot(data = dailydesc_filter, aes(x = reorder(months, month), y = shannon, fill = Site)) +
  geom_boxplot() +
  xlab("Months") +
  ylab("Shannon Index of Diversity") + 
  labs(fill = "Site") +
  ggtitle("Compare the difference in Shannon index of diversity between phytoplankton species between 
          the two sites, for three consecutive months of 2019") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))






## DOMINANT SPECIES DENSITIES BETWEEN SITES --------------------------------




#'* used to back up ind spe graph (Aim 2), can possibly do stats on this ---------*
# [Stacked bar graph] comparing PS and ADf biomass on monthly level (more broad than above)
Sp.only_filter %>% 
  group_by(Site, months, month) %>% 
  summarise(monthly.mean = mean(meanCells, na.rm = TRUE)) %>% 
  ggplot(., aes(x = reorder(months, month), y = monthly.mean, fill = Site)) +
  geom_bar(stat = "Identity", position = "fill") +
  geom_hline(yintercept = 0.5, col = "black") +
  xlab("Months") +
  ylab("Proportion momthly mean Cells/L") + 
  labs(fill = "Site") +
  ggtitle("The proportion of cells counted between the Primary sump and After Drumfilter 
          for three consecutive months of 2019") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))




#'* Graph for Aim 2 -----------*
# [Stacked bargraph] of Top n species, comparing monthly averages between two sites
Sp.only_filter %>% 
  group_by(Site, months, month, Species, Classification) %>% 
  summarise(monthly.mean = mean(meanCells, na.rm = TRUE)) %>% 
  filter(Species %in% top_species$Species) %>% 
  ggplot(., aes(x = reorder(months, month), y = monthly.mean, fill = Site)) +
  geom_bar(stat = "Identity", position = "fill") +
  geom_hline(yintercept = 0.5, col = "black") +
  #coord_flip() +
  facet_wrap(~ reorder(Species, -monthly.mean), ncol = 2) +
  xlab("Months") +
  ylab("Proportion momthly mean Cells/L") + 
  labs(fill = "Site") +
  ggtitle("The proportion of cells counted between the Primary sump and After Drumfilter for the 
          top four dominant species for three consecutive months of 2019") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
 plots

Sp.only_filter %>% 
  group_by(Site, months, month, Species, Classification) %>% 
  summarise(monthly.mean = mean(meanCells, na.rm = TRUE)) %>% 
  filter(Species %in% top_species$Species)








```


## Chapter 3 stats


```{r Chapter 3}
#### significant difference between biomass in different sites  ####

# calculate descriptive stats
Sp.only_filter %>% 
  group_by(Site, months) %>% 
  summarise(mean_cells = mean(meanCells, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(meanCells, na.rm = TRUE), 
            se_cells = sd(meanCells, na.rm = TRUE)/sqrt(n())) %>% 
  view()

### Total significance? 

total_sp_filter %>% 
  select(Site, total_biomass) %>% 
  dunn_test(total_biomass ~ Site, p.adjust.method = "bonferroni") %>% 
  view()


# Feb signif
total_sp_filter %>% 
  filter(months == "February") %>% 
  select(Site, total_biomass) %>% 
  dunn_test(total_biomass ~ Site, p.adjust.method = "bonferroni")


# March signif
total_sp_filter %>% 
  filter(months == "March") %>% 
  select(Site, total_biomass) %>% 
  dunn_test(total_biomass ~ Site, p.adjust.method = "bonferroni")


# April signif
total_sp_filter %>% 
  filter(months == "April") %>% 
  select(Site, total_biomass) %>% 
  dunn_test(total_biomass ~ Site, p.adjust.method = "bonferroni")



## richness sig dif ######

dailydesc_filter %>% 
  view()

# Total sig dif
dailydesc_filter %>% 
  select(Site, S) %>% 
  dunn_test(S ~ Site, p.adjust.method = "bonferroni")


# Feb

dailydesc_filter %>% 
  filter(months == "February") %>% 
  select(Site, S) %>% 
  dunn_test(S ~ Site, p.adjust.method = "bonferroni")

# March 
dailydesc_filter %>% 
  filter(months == "March") %>% 
  select(Site, S) %>% 
  dunn_test(S ~ Site, p.adjust.method = "bonferroni")

# April
dailydesc_filter %>% 
  filter(months == "April") %>% 
  select(Site, S) %>% 
  dunn_test(S ~ Site, p.adjust.method = "bonferroni")






## evenness sig dif ####

# Total sig dif
dailydesc_filter %>% 
  select(Site, J) %>% 
  dunn_test(J ~ Site, p.adjust.method = "bonferroni")

# Feb
dailydesc_filter %>% 
  filter(months == "April") %>% 
  select(Site, J) %>% 
  dunn_test(J ~ Site, p.adjust.method = "bonferroni")

# March 
dailydesc_filter %>% 
  filter(months == "March") %>% 
  select(Site, J) %>% 
  dunn_test(J ~ Site, p.adjust.method = "bonferroni")

# April
dailydesc_filter %>% 
  filter(months == "April") %>% 
  select(Site, J) %>% 
  dunn_test(J ~ Site, p.adjust.method = "bonferroni")

## diversity sig dif #####

# Total sig dif
dailydesc_filter %>% 
  select(Site, shannon) %>% 
  dunn_test(shannon ~ Site, p.adjust.method = "bonferroni")

# Feb
dailydesc_filter %>% 
  filter(months == "February") %>% 
  select(Site, shannon) %>% 
  dunn_test(shannon ~ Site, p.adjust.method = "bonferroni")

# March
dailydesc_filter %>% 
  filter(months == "March") %>% 
  select(Site, shannon) %>% 
  dunn_test(shannon ~ Site, p.adjust.method = "bonferroni")

# April
dailydesc_filter %>% 
  filter(months == "April") %>% 
  select(Site, shannon) %>% 
  dunn_test(shannon ~ Site, p.adjust.method = "bonferroni")



#### Species change betwen sites #####

## P. micans 

# total biommass for species over sites
P.m_only <- Sp.only_filter %>% 
  filter(Species == "Prorocentrum micans") %>% 
  ungroup() 

P.m_only %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")

# Monthly
# Feb

# descriptive statistics ( used to justify p-values)
P.m_only %>% 
  filter(months == "February") %>% 
  group_by(Site) %>% 
  summarise(me = mean(meanCells, na.rm = TRUE), 
            se = sd(meanCells, na.rm = TRUE)/sqrt(n())) 

# sig dif
P.m_only %>% 
  filter(months == "February") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")

# March

# sig dif
P.m_only %>% 
  filter(months == "March") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")

# April
# sig dif
P.m_only %>% 
  filter(months == "April") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")





## L. polyedra

# total biommass for species over sites
L.p_only <- Sp.only_filter %>% 
  filter(Species == "Lingulodinium polyedra") %>% 
  ungroup() 

# Feb
# sig dif
L.p_only %>% 
  filter(months == "February") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")

# March
# sig dif
L.p_only %>% 
  filter(months == "March") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")

# April
# sig dif
L.p_only %>% 
  filter(months == "April") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")



## G. polygramma

# total biommass for species over sites
G.p_only <- Sp.only_filter %>% 
  filter(Species == "Gonyaulax polygramma") %>% 
  ungroup() 


# Feb
# sig dif
G.p_only %>% 
  filter(months == "February") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")

# March
# sig dif
G.p_only %>% 
  filter(months == "March") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")



# April
# sig dif
G.p_only %>% 
  filter(months == "April") %>% 
  select(Site, meanCells) %>% 
  dunn_test(meanCells ~ Site, p.adjust.method = "bonferroni")





#### Which species are significantly reduced between the PS and ADf? #####

# Pivot species wide
# calculate descriptive on monthly level between sites, for each species
# plot
# decide which species to extract
# do sig dif for top two

# Which species have biggest range between sites?


Sp.only_filter %>% 
  ungroup() %>% 
  select(Date, months, Site, Species, meanCells) %>% 
  pivot_wider(names_from = Site, values_from = meanCells, values_fill = list(meanCells = 0)) %>% 
  mutate(differ = `Primary sump` - `After Drumfilter`) %>% 
  arrange(desc(differ)) %>% 
  view()



Sp.only_filter %>% 
  ungroup() %>% 
  select(Date, months, Site, Species, meanCells) %>% 
  pivot_wider(names_from = Species, values_from = meanCells, values_fill = list(meanCells = 0)) %>% 
  view()




trans <- Sp.only_filter %>% 
  mutate(meanCells = log10(meanCells))

all_sp_feb <- trans %>% 
  ungroup() %>% 
  mutate(Sp_site = paste(Species, Site, sep = "_")) %>% 
  filter(months == "February") %>% 
  select(meanCells, Sp_site) %>% 
  dunn_test(meanCells ~ Sp_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

feb_sig <- trans %>% 
  ungroup() %>% 
  mutate(Sp_site = paste(Species, Site, sep = "_")) %>% 
  filter(months == "February") %>% 
  select(meanCells, Sp_site) %>% 
  dunn_test(meanCells ~ Sp_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

march_sig <- trans %>% 
  ungroup() %>% 
  mutate(Sp_site = paste(Species, Site, sep = "_")) %>% 
  filter(months == "March") %>% 
  select(meanCells, Sp_site) %>% 
  dunn_test(meanCells ~ Sp_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

apr_sig <- trans %>% 
  ungroup() %>% 
  mutate(Sp_site = paste(Species, Site, sep = "_")) %>% 
  filter(months == "April") %>% 
  select(meanCells, Sp_site) %>% 
  dunn_test(meanCells ~ Sp_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")


# all_sp_feb %>%
#   filter(substr(group1, 1, 10) == substr(group2, 1, 10))




pairwise.wilcox.test(all_sp_feb$meanCells, all_sp_feb$Species, p.adjust.method = "bonf")


## Classification

cl <- Sp.only_filter %>% 
  mutate(meanCells = log10(meanCells))

cl %>% 
  ungroup() %>% 
  mutate(cl_site = paste(Classification, Site, sep = "_")) %>% 
  # filter(months == "February") %>% 
  select(meanCells, cl_site) %>% 
  dunn_test(meanCells ~ cl_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")


cl.feb_sig <- cl %>% 
  ungroup() %>% 
  mutate(cl_site = paste(Classification, Site, sep = "_")) %>% 
  filter(months == "February") %>% 
  select(meanCells, cl_site) %>% 
  dunn_test(meanCells ~ cl_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

cl.march_sig <- cl %>% 
  ungroup() %>% 
  mutate(cl_site = paste(Species, Site, sep = "_")) %>% 
  filter(months == "March") %>% 
  select(meanCells, cl_site) %>% 
  dunn_test(meanCells ~ cl_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

cl.apr_sig <- cl %>% 
  ungroup() %>% 
  mutate(cl_site = paste(Species, Site, sep = "_")) %>% 
  filter(months == "April") %>% 
  select(meanCells, cl_site) %>% 
  dunn_test(meanCells ~ cl_site, p.adjust.method = "bonferroni") %>% 
  arrange(desc(-p.adj)) %>% 
  filter(p.adj.signif != "ns")

```





## Total Abundance
#### Fix data frame ##
```{r}

df <- read.csv("Oct 2020/2017.2019.OR/written_df_Oct.csv")

# fix date
df$Date <- as.Date(df$Date, "%Y/%m/%d")

# add month and year columns 
df <- df %>% 
  mutate(months = months(Date), month = month(Date), year = year(Date), YEarMonth = as.yearmon(paste(year, month), "%Y %m"))

# merge date and times and coerce to proper format 
df$dateTime <- as.POSIXct(paste(df$Date, df$Time), format = "%Y-%m-%d %H:%M")

# coerce year column as factor
df$year <- as.factor(df$year)

correct_dates <- df %>% 
  filter(Date >= "2019-02-01" & Date <= "2019-04-30") %>%
  filter(Site %in% c("Primary sump", "After Drumfilter")) %>% 
  select(Date, Time, Site, Correct.Original) %>%
  group_by(Date, Site) %>% 
  summarise(sumC = sum(Correct.Original, na.rm = TRUE)) %>% 
  # group_by(Date, Site) %>% 
  # summarise(meanC = mean(sumC, na.rm = TRUE)) %>% 
  pivot_wider(names_from = Site, values_from = sumC, 
              values_fil = list(sumC = 0)) %>%
  filter(`After Drumfilter` != "NA", `After Drumfilter` != 0)


# create a df to use as a basis
main_df <- df %>% 
  filter(Date %in% correct_dates$Date) %>% 
  filter(Site %in% c("After Drumfilter", "Primary sump")) %>% 
  filter(Classification != "Ciliate", 
         Classification != "Spirotrichea", 
         Classification != "Litostomatea")

# correct the order of sites (PS before ADf)
main_df$Site <- as.factor(main_df$Site)
main_df$Site <-  factor(main_df$Site, 
                       levels = c("Primary sump", "After Drumfilter"))

# Create species df
species_df <- main_df %>% 
  group_by(Date, Site, Species, Classification, months, month, year) %>% 
  summarise(meanCells = mean(Correct.Original, na.rm = TRUE)) %>% 
  filter(Classification != "Various", 
         Species != "Diatom")


# daily richness
daily_richness <- species_df %>%
  group_by(Date, Site) %>% 
  summarise(S = n_distinct(Species))


# diversity
# pivot species wider
div_filter <- species_df %>% 
  ungroup() %>% 
  select(Date, Site, Species, meanCells) %>% 
  pivot_wider(names_from = Species, values_from = meanCells, 
              values_fill = list(meanCells = 0))

# create group
group_filter <- div_filter %>% 
  select(Date, Site)

# diversity for each day, and site
group_filter <- group_filter %>% 
  mutate(shannon2 = diversity(div_filter[, 3:ncol(div_filter)], "shannon", base = 2),
       shannon = diversity(div_filter[, 3:ncol(div_filter)], "shannon"),
       simpson = diversity(div_filter[, 3:ncol(div_filter)], "simpson"), 
       Inv_simpson = diversity(div_filter[, 3:ncol(div_filter)], "inv"))


# Join all metrics 
# Create evennes metric
daily_metrics <- left_join(group_filter, daily_richness, by = c("Date", "Site")) %>% 
  mutate(J2 = shannon2/log(S), 
       J = shannon/log(S))

# Create total abundance df
total_abun <- main_df %>% 
  group_by(Date, Time, Site, months, month) %>% 
  summarise(sumC = sum(Correct.Original, na.rm = TRUE)) %>% 
  group_by(Date, Site, months, month) %>% 
  summarise(meanC = mean(sumC, na.rm = TRUE))


```

## Plot data ###

```{r}

main_df %>% 
  group_by(Date, Time, months, month, Site) %>% 
  summarise(sumC = sum(Correct.Original, na.rm = TRUE)) %>% 
  group_by(Date, months, month, Site) %>% 
  summarise(meanC = mean(sumC, na.rm = TRUE)) %>% 
  group_by(months, month, Site) %>% 
  summarise(mean_cells = mean(meanC, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(meanC, na.rm = TRUE), 
            se_cells = sd(meanC, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = mean_cells, col = Site, group = Site)) +
  geom_point() +
#  geom_line() +
  geom_errorbar(aes(ymin = mean_cells - se_cells, ymax = mean_cells + se_cells), width=0.2) +
  xlab("Months") +
  ylab("Cells/L") + 
  labs(fill = "Site") +
#  ggtitle("") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

total_abun %>% 
  group_by(months, month, Site) %>% 
  summarise(mean_cells = mean(meanC, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(meanC, na.rm = TRUE), 
            se_cells = sd(meanC, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = mean_cells, col = Site, group = Site)) +
  geom_point() +
#  geom_line() +
  geom_errorbar(aes(ymin = mean_cells - se_cells, ymax = mean_cells + se_cells), width=0.2) +
  xlab("Months") +
  ylab("Cells/L") + 
  labs(fill = "Site") +
#  ggtitle("") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))


## Classification differences between Diatoms and Dino's
main_df %>% 
  filter(Classification != "Various", 
         Species != "Diatom", 
         Classification != "Dictyochophyceae") %>% 
  group_by(Date, Time, Site, months, month, Classification) %>% 
  summarise(sumC = sum(Correct.Original, na.rm = TRUE)) %>% 
  group_by(Date, Site, months, month, Classification) %>% 
  summarise(meanC = mean(sumC, na.rm = TRUE)) %>% 
  group_by(Classification, months, month, Site) %>% 
  summarise(mean_cells = mean(meanC, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(meanC, na.rm = TRUE), 
            se_cells = sd(meanC, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = mean_cells, col = Site, group = Site)) +
  geom_point() +
#  geom_line() +
  geom_errorbar(aes(ymin = mean_cells - se_cells, ymax = mean_cells + se_cells), width=0.2) +
  facet_wrap(~Classification, scales = "free_y", ncol = 1) + 
  xlab("Months") +
  ylab("Cells/L") + 
  labs(fill = "Site") +
#  ggtitle("") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))



## Dominant species

dominant_species <- main_df %>% 
  filter(Classification != "Various") %>% 
  group_by(Species) %>% 
  summarise(meanC = mean(Correct.Original, na.rm = TRUE)) %>% 
  arrange(desc(meanC)) %>%
  ungroup() %>% 
  top_n(3)

main_df %>% 
  filter(Species %in% dominant_species$Species) %>% 
  group_by(Date, Site, Species, months, month) %>% 
  summarise(meanC = mean(Correct.Original, na.rm = TRUE)) %>%
  group_by(Site, Species, months, month) %>% 
  summarise(mean_cells = mean(meanC, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(meanC, na.rm = TRUE), 
            se_cells = sd(meanC, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = mean_cells, col = Site, group = Site)) +
  geom_point() +
#  geom_line() +
  geom_errorbar(aes(ymin = mean_cells - se_cells, ymax = mean_cells + se_cells), width=0.2) +
  facet_wrap(~Species, scales = "free_y", ncol = 1) + 
  xlab("Months") +
  ylab("Cells/L") + 
  labs(fill = "Site") +
#  ggtitle("") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))


main_df %>% 
  filter(Species %in% dominant_species$Species) %>% 
  group_by(Date, Site, Species, months, month) %>% 
  summarise(meanC = mean(Correct.Original, na.rm = TRUE)) %>%
  group_by(Site, Species, months, month) %>% 
  summarise(mean_cells = mean(meanC, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(meanC, na.rm = TRUE), 
            se_cells = sd(meanC, na.rm = TRUE)/sqrt(n())) %>% 
  view()


main_df %>% 
  filter(Species == "Gonyaulax polygramma") %>% 
  group_by(Date, Site, Species, months, month) %>% 
  summarise(meanC = mean(Correct.Original, na.rm = TRUE)) %>% 
  ggplot(., aes(x = Date, y = meanC, col = Site)) +
  geom_line() +
  scale_y_log10()

## Community metrics

# Richness
daily_metrics %>%
  mutate(months = months(Date), month = month(Date)) %>% 
  group_by(Site, months, month) %>% 
  summarise(mean_cells = mean(S, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(S, na.rm = TRUE), 
            se_cells = sd(S, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = mean_cells, col = Site, group = Site)) +
  geom_point() +
#  geom_line() +
  geom_errorbar(aes(ymin = mean_cells - se_cells, ymax = mean_cells + se_cells), width=0.2) + 
  xlab("Months") +
  ylab("Species Richness") + 
  labs(fill = "Site") +
#  ggtitle("") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))


# Evenness
daily_metrics %>%
  mutate(months = months(Date), month = month(Date)) %>% 
  group_by(Site, months, month) %>% 
  summarise(mean_cells = mean(J, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(J, na.rm = TRUE), 
            se_cells = sd(J, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = mean_cells, col = Site, group = Site)) +
  geom_point() +
#  geom_line() +
  geom_errorbar(aes(ymin = mean_cells - se_cells, ymax = mean_cells + se_cells), width=0.2) + 
  xlab("Months") +
  ylab("Pielou's Evenness") + 
  labs(fill = "Site") +
#  ggtitle("") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))


# Shannon diversity
daily_metrics %>%
  mutate(months = months(Date), month = month(Date)) %>% 
  group_by(Site, months, month) %>% 
  summarise(mean_cells = mean(shannon, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(shannon, na.rm = TRUE), 
            se_cells = sd(shannon, na.rm = TRUE)/sqrt(n())) %>% 
  ggplot(., aes(x = reorder(months, month), y = mean_cells, col = Site, group = Site)) +
  geom_point() +
#  geom_line() +
  geom_errorbar(aes(ymin = mean_cells - se_cells, ymax = mean_cells + se_cells), width=0.2) + 
  xlab("Months") +
  ylab("Shannon-Weiner") + 
  labs(fill = "Site") +
#  ggtitle("") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

```



## Stats on data ####

```{r}

## Total abundance
total_abun %>% 
  ungroup() %>% 
  filter(months == "April") %>% 
  select(Site, meanC) %>% 
  dunn_test(meanC ~ Site, p.adjust.method = "bonferroni")

# Compare on a large scale between sites
main_df %>% 
  group_by(Date, Time, months, month, Site) %>% 
  summarise(sumC = sum(Correct.Original, na.rm = TRUE)) %>% 
  group_by(Date, Site, months, month) %>% 
  summarise(meanC = mean(sumC, na.rm = TRUE)) %>% 
  group_by(Site) %>% 
  summarise(mean_cells = mean(meanC, na.rm = TRUE), 
            n_cells = n(),
            sd_cells = sd(meanC, na.rm = TRUE), 
            se_cells = sd(meanC, na.rm = TRUE)/sqrt(n())) %>% 
 ggplot(., aes(x = Site, y = mean_cells, col = Site, group = Site)) +
  geom_point() +
#  geom_line() +
  geom_errorbar(aes(ymin = mean_cells - se_cells, ymax = mean_cells + se_cells), width=0.2) +
  xlab("Months") +
  ylab("Cells/L") + 
  labs(fill = "Site") +
#  ggtitle("") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

## Functional group differences 
main_df %>% 
  filter(Classification != "Various", 
         Species != "Diatom", 
         Classification != "Dictyochophyceae") %>% 
  group_by(Date, Time, Site, months, month, Classification) %>% 
  summarise(sumC = sum(Correct.Original, na.rm = TRUE)) %>% 
  group_by(Date, Site, months, month, Classification) %>% 
  summarise(meanC = mean(sumC, na.rm = TRUE)) %>% 
  group_by(Classification, months, month, Site) %>% 
  filter(Classification == "Dinoflagellate", 
         months == "April") %>%
  ungroup() %>% 
  dunn_test(meanC ~ Site, p.adjust.method = "bonferroni")


## Dominant Species
main_df %>% 
  filter(Species %in% dominant_species$Species) %>% 
  group_by(Date, Site, Species, months, month) %>% 
  summarise(meanC = mean(Correct.Original, na.rm = TRUE)) %>% 
  filter(Species == "Lingulodinium polyedra", 
         months == "February") %>% 
  ungroup() %>% 
  dunn_test(meanC ~ Site, p.adjust.method = "bonferroni")


## Community metrics

daily_metrics %>%
  mutate(months = months(Date), month = month(Date)) %>% 
  ungroup() %>% 
  #filter(months == "February") %>% 
  dunn_test(shannon ~ Site, p.adjust.method = "bonferroni")

```










